### ISSUE TITLE
Comments inbetween NAG 

### ISSUE THREAD

**Issue by kapcabbage** [mliebelt/PgnViewerJS#100]
PGN cannot be parsed correctly if there are comments inbetween NAG's 
for example `Qh4 {!}$15 {/}$17` would yield an error.

**Comment by mliebelt** [comment]
Sorry, had no time to answer. I will look into the topic, but when I take your example and create a study in lichess.org with your example, this fails. So I think mixing comments and NAGs is pretty unusual, and may fail for a lot of PGN software systems.
But I will give it a try, if there could be a solution.

**Comment by kapcabbage** [comment]
No problem. I am basing my comment on Chess Assistant and it is possible there (don't know whats is the version though - might be 14 or so). Sadly I couldn't find any information regarding NAG and comment order so I can't really tell if it's correct or not to mix NAG's and comments.  

I really appreciate your work, good job :)

**Comment by mliebelt** [comment]
I read the specification (http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c5, then chapter 7 about tokens) again, and it seems that it would be possible to have comments in between tokens. But this gives me major headaches, so I will ignore that.

2 reasons:

* It is nearly impossible to make an editor to have that as option.
* I have no real usage for having comments between NAGs.

So this feature request will be closed without an implementation.
