### ISSUE TITLE
Loading inital positions

### ISSUE THREAD

**Issue by kapcabbage** [mliebelt/PgnViewerJS#104]
Hello there,

There is an issue regarding loading games. If initial position is declared - either by `position: fen` or by `[SetUp "1"][FEN "fen"]` the game cannot be loaded correctly. 

Example error: 
`PGN: [Event "Match"] [Site "Sveti-Stefan/Belgrade (Yugoslavia)"] [Date "1992.??.??"] [Round "7"] [White "Fischer Robert J (USA)"] [Black "Spassky Boris V (FRA)"] [Result "1-0"] [ECO "C90"] [WhiteElo "2785"] [BlackElo "2560"] [Annotator ""] [Source ""] [Remark "IX-XI"] [SetUp "1"] [FEN "8/3P1kP1/5b2/pp3N2/8/3K4/P7/8 b - - 0 44"] 1.e4 e5 2.Nf3 $14 Nc6 3.Bb5 a6 4.Ba4 Nf6 5.O-O Be7 6.Re1 b5 7.Bb3 d6 8.c3 O-O 9.d3 Na5 10.Bc2 c5 11.Nbd2 Re8 12.h3 Bf8 13.Nf1 Bb7 14.Ng3 g6 15.Bg5 h6 16.Bd2 d5 17.exd5 c4 18.b4 cxd3 19.Bxd3 Qxd5 20.Be4 Nxe4 21.Nxe4 Bg7 22.bxa5 f5 23.Ng3 e4 24.Nh4 Bf6 25.Nxg6 e3 26.Nf4 Qxd2 27.Rxe3 Qxd1+ 28.Rxd1 Rxe3 29.fxe3 Rd8 30.Rxd8+ Bxd8 31.Nxf5 Bxa5 32.Nd5 Kf8 33.e4 Bxd5 34.exd5 h5 35.Kf2 Bxc3 36.Ke3 Kf7 37.Kd3 Bb2 38.g4 hxg4 39.hxg4 Kf6 40.d6 Ke6 41.g5 a5 42.g6 Bf6 43.g7 Kf7 44.d7 1-0
No legal move: e4` 

With given FEN:
` [SetUp "1"]
    [FEN "8/3P1kP1/5b2/pp3N2/8/3K4/P7/8 b - - 0 44"]`

**Comment by kapcabbage** [comment]
I think I've misunderstood the premise of `position: `. Now I get it. It means the initial position of a match, not initial position showed on board.

**Comment by mliebelt** [comment]
See the ticket #46 that describes the feature you want to have. I will add there comments, ...

**Comment by mliebelt** [comment]
Last commit should be the solution you wanted. Use `startPlay: '8/3P1kP1/5b2/pp3N2/8/3K4/P7/8 b'` in the configuration.
