### ISSUE TITLE
Parser: comment on Black's move starting a variation

### ISSUE THREAD

**Issue by bulldozer75** [mliebelt/PgnViewerJS#105]
A comment on a Black's move that starts a variation is mistakenly ignored by the parser.
For instance, `b-comment2` is ignored in the following game while other two comments are ok:
`1. d4 ({w-comment} e4 {b-comment1} e5) Nf6 ({b-comment2} d5)`

A minimal failing example:
`1. d4 Nf6 ({b-comment} d5)`

Steps to reproduce:
 * Go to https://pegjs.org/online
 * Paste the distribution's `pgn-rules.peg` into Window 1
 * Paste the following `1. d4 Nf6 ({b-comment} d5)` into Window 2
 What is expected:
"b-comment" must appear in the JSON in the Window 3
 What happens:
"b-comment" is missing in the JSON in the Window 3

Possible fix:
The `pgnWhite = ` statement in the grammar contains the following piece:
``` move.commentMove = cm;```
The Black's section is missing that piece. Maybe because the author thought that the Black's comments were covered by the White's `commentAfter`. But this is not the case at the beginning of a variation.
I've tried to add that piece, and everything looked fine. Haven't tested much though.

**Comment by mliebelt** [comment]
Strange UI effects on closing, sorry for the additional opening / closing.
