### ISSUE TITLE
En passant is not working well

### ISSUE THREAD

**Issue by cobra0901** [mliebelt/PgnViewerJS#108]
Hello
Dear mliebelt.
I am very interested your library.
But En passant is not working well
Can you help me?

**Comment by cgencer** [comment]
I was going to write the same, en passant wasn't working...

**Comment by mliebelt** [comment]
I noticed that there is also wrong notation for en passent emmitted (first).  So I should fix that as well ...

**Comment by EugenePizzerbert** [comment]
Dear mliebelt.
I checked your sayings step by step.
You said that "When I use the pgnEdit mode, I am able to enter moves that result in the following pgn: 1. e4 e5 2. f4 exf4 3. g4 fxg3 4. Nf3. But after move fxg3, the white pawn on g4 is left on the board."-This is perfect
I think that it is ok if g4 pawn image is removed on chess board.
By the way, I wish your suggestion asap.

**Comment by EugenePizzerbert** [comment]
I closed this chat.
No way to find more yet.

**Comment by mliebelt** [comment]
I fixed the error in the development version. If you want to know how to create a new version, please read https://github.com/mliebelt/PgnViewerJS/blob/master/dev.md how to use the examples. I have created a file `ticket108.html` that demonstrates en passant in `viewMode` and `editMode`.

**Comment by EugenePizzerbert** [comment]
Excellent 
En passant is working well.
Thanks for your help.
I recommend you
👏

**Comment by HoldYourWaffle** [comment]
Shouldn't this be closed now?

**Comment by mliebelt** [comment]
Yes. @EugenePizzerbert You may comment on closed issues as well, you don't have to open them.

**Comment by mliebelt** [comment]
Broken again, will  be fixed during cleanup.
