### ISSUE TITLE
how to apply tactics 

### ISSUE THREAD

**Issue by Abdofcih** [mliebelt/PgnViewerJS#113]
now i create my android app using javascript for showing games and strategy
and i need to create my second app as tactics puzzles can you recommend me a library to help doing that

**Comment by mliebelt** [comment]
Well, not really. I have implemented a PgnViewer, so this will be of course part of the game. But I cannot say anything about the needed additions, and if the public interface I propose will help you implement it. So, sorry, I cannot help here. I will close therefore the ticket.
