### ISSUE TITLE
Reading of NAGs with symbol characters and comments in between

### ISSUE THREAD

**Issue by tilvan** [mliebelt/PgnViewerJS#120]
Hi @mliebelt!
I'm new with PGN and I have an issue with PGN parser with `pgn.js`.
I have PGN fragment `1.Bxc4 d5 2.Bxd5 Qxd5 3.a5 {!} $16` - and here I have parser exception with message from `pgnvjs.js`
```
Expected " ", "(", ")", "*", "0-1", "0:1", "1-0", "1/2-1/2", "1:0", "O-O", "O-O-O", "x", "{", [RNBQKP], [a-h], or integer but "$" found.
```
How can I fix it with current configuration?

**Comment by mliebelt** [comment]
The reason for that is, that the PgnViewerJS currently does not accept comments at any point. Here are the options that will work:

* Before the move number: `{! this is a comment } 1.e4 $16`
* After the move number: `1. {! this is a comment } e4 $16`
* After the complete move: `1. e4 $16  {! this is a comment }` (including the NAGs)

You can check that yourself with the configuration builder: https://mliebelt.github.io/PgnViewerJS/docu/example/config.html

I will check the grammar if it is easy to add comments between move and NAGs, but this may be endless. Something like `1. e4 ! { good move} ? { but I don't like it }` would be a nightmare to parse.

**Comment by mliebelt** [comment]
Well, after changing the grammar again and again, I am pretty sure that I will never ever implement that feature. Not only the reading will be a nightmare, but also the print-out. So i will close that ticket without a fix. Sorry!
