### ISSUE TITLE
Chess clock support

### ISSUE THREAD

**Issue by awormuth** [mliebelt/PgnViewerJS#122]
It it possible to support chess clocks? 

Here is some sample PGN data:

[Event "2019 Sinquefield Cup"]
[Site "Saint Louis"]
[Date "2019.08.17"]
[Round "1.1"]
[White "Carlsen, Magnus"]
[Black "Giri, Anish"]
[Result "1/2-1/2"]
[BlackElo "2759"]
[WhiteElo "2873"]
[LiveChessVersion "1.4.8"]
[ECO "A28"]

1. c4 {[%clk 2:10:30]} Nf6 {[%clk 2:10:30]} 2. Nc3 {[%clk 2:10:30]} e5
{[%clk 2:10:30]} 3. Nf3 {[%clk 2:10:30]} Nc6 {[%clk 2:10:30]} 4. e4
{[%clk 2:10:30]} Bb4 {[%clk 2:10:17]} 5. d3 {[%clk 2:10:30]} d6 {[%clk 2:09:44]}
6. Be2 {[%clk 2:09:30]} Bg4 {[%clk 2:04:10]} 7. a3 {[%clk 1:58:09]} Bc5
{[%clk 2:01:23]} 8. b4 {[%clk 1:58:09]} Bb6 {[%clk 2:00:50]} 9. Be3
{[%clk 1:57:45]} Bxf3 {[%clk 1:54:59]} 10. Bxf3 {[%clk 1:57:45]} Nd4
{[%clk 1:54:59]} 11. Na4 {[%clk 1:56:57]} Nxf3+ {[%clk 1:52:35]} 12. Qxf3
{[%clk 1:56:57]} Bxe3 {[%clk 1:52:35]} 13. Qxe3 {[%clk 1:56:33]} O-O
{[%clk 1:39:51]} 14. O-O {[%clk 1:56:29]} Re8 {[%clk 1:26:49]} 15. Nc3
{[%clk 1:45:44]} a5 {[%clk 1:16:33]} 16. b5 {[%clk 1:29:53]} c6 {[%clk 1:15:50]}
17. Rab1 {[%clk 1:28:35]} d5 {[%clk 1:12:35]} 18. Na4 {[%clk 1:28:30]} Qe7
{[%clk 1:06:54]} 19. bxc6 {[%clk 1:27:47]} bxc6 {[%clk 1:06:40]} 20. cxd5
{[%clk 1:27:47]} cxd5 {[%clk 1:06:34]} 21. Nb6 {[%clk 1:27:47]} Rad8
{[%clk 1:04:57]} 22. Rb5 {[%clk 1:27:47]} Qxa3 {[%clk 1:02:59]} 23. exd5
{[%clk 1:26:35]} e4 {[%clk 1:01:26]} 24. dxe4 {[%clk 1:18:29]} Qxe3
{[%clk 1:01:26]} 25. fxe3 {[%clk 1:18:29]} Rxe4 {[%clk 0:56:46]} 26. Rxa5
{[%clk 1:18:29]} Rb4 {[%clk 0:50:11]} 27. Ra8 {[%clk 1:17:40]} Rxa8
{[%clk 0:47:30]} 28. Nxa8 {[%clk 1:17:40]} Nxd5 {[%clk 0:47:30]} 29. Rd1
{[%clk 1:17:40]} Rb8 {[%clk 0:47:30]} 30. Rxd5 {[%clk 1:17:40]} Rxa8
{[%clk 0:47:30]} 31. Kf2 {[%clk 1:17:40]} Kf8 {[%clk 0:47:30]} 32. Kf3
{[%clk 1:17:40]} h6 {[%clk 0:47:30]} 33. Kf2 {[%clk 1:17:40]} Ra2+
{[%clk 0:47:30]} 34. Kf3 {[%clk 1:17:40]} Ra8 {[%clk 0:47:30]} 35. Kf2
{[%clk 1:17:40]} Ra2+ {[%clk 0:47:30]} 36. Kf3 {[%clk 1:17:40]} Ra8 1/2-1/2

And here is how it renders:
<img width="337" alt="Screen Shot 2019-08-25 at 12 15 00 AM" src="https://user-images.githubusercontent.com/2530972/63646804-68c75500-c6cd-11e9-9b7f-230512a0c9f6.png">

Do you have any thoughts or suggestions for improving the UI of clocks?

**Comment by mliebelt** [comment]
Well, my thoughts here are:
* This is a special format (found it on chess.com, there may be similar formats available from other sites).
* I don't think that this is any standard (at least it is not found in http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm)

**Comment by gbtami** [comment]
This is widely used by all sites broadcasting tournaments in .pgn format. Lichess uses %eval and %clock also at https://database.lichess.org/
See http://www.enpassant.dk/chess/palview/enhancedpgn.htm

**Comment by mliebelt** [comment]
Interesting kind of a specification, did not know that. I have to study it, and see if there is a way to make a more abstract rule set that allows any "commands" as part of comments. Currently, only the graphical symbols `csl` and `cal` are supported (which render colored fields and arrows).

The change would mean, that the grammar ready any command, and there should be then a command parser that allows to convert the read things in something usable for the PgnViewerJS.

I don't like another special implementation, that leads to more special code, which is more difficult to change later.

**Comment by mliebelt** [comment]
Here is the first rough screenshot how it could behave
![image](https://user-images.githubusercontent.com/520039/64486880-307a5780-d233-11e9-97e2-6ec85e42d904.png)

The configuration is the following:
* timeAnnotation: 'timeNormal'
* timeAnnotation: 'timeTiny'
* no configuration (default is to hide the time)

What I would like to add is:

* Allow to define what kind of time to show: rest time, spent time, spent time move
* (later) show the time in a different view (if the viewer wants it) like done on lichess
