### ISSUE TITLE
Invalid PGN

### ISSUE THREAD

**Issue by awormuth** [mliebelt/PgnViewerJS#124]
Hello, do you have any insight into what the problem is with this PGN game? It cannot be parsed in it's current state

[ePGN "0.1;DGT LiveChess/2.2.4"]
[Event "FIDE Chess.com Grand Swiss"]
[Site "Comis Hotel, Isle Of Man"]
[Date "2019.10.20"]
[Round "10.1"]
[White "Caruana, Fabiano"]
[Black "Anton Guijarro, David"]
[Result "1-0"]
[WhiteElo "2812"]
[BlackElo "2674"]

1.c4 {[%emt 00:02:29]} e5 {[%emt 00:00:19]} 2.Nc3 {[%emt 00:00:06]} Nc6 {[%emt 00:00:21]} 3.Nf3 {[%emt 00:00:13]} g6 {[%emt 00:00:47]} 4.d4 {[%emt 00:00:09]} exd4 {[%emt 00:00:08]} 5.Nxd4 {[%emt 00:00:05]} Bg7 {[%emt 00:00:20]} 6.Nxc6 {[%emt 00:00:07]} dxc6 {[%emt 00:00:13]} 7.Qxd8+ {[%emt 00:01:09]} Kxd8 {[%emt 00:00:05]} 8.Bg5+ {[%emt 00:12:15]} Ke8 {[%emt 00:00:14]} 9.O-O-O {[%emt 00:00:26]} Be6 {[%emt 00:00:13]} 10.e4 {[%emt 00:00:50]} Bh6 {[%emt 00:00:24]} 11.Bxh6 {[%emt 00:04:55]} Nxh6 {[%emt 00:00:07]} 12.Be2 {[%emt 00:02:01]} Ke7 {[%emt 00:02:35]} 13.b3 {[%emt 00:02:47]} f6 {[%emt 00:03:32]} 14.h4 {[%emt 00:04:51]} Nf7 {[%emt 00:03:20]} 15.f4 {[%emt 00:01:10]} h5 {[%emt 00:02:11]} 16.Bf3 {[%emt 00:05:30]} a5 {[%emt 00:11:42]} 17.Rhe1 {[%emt 00:08:16]} Bg4 {[%emt 00:02:01]} 18.Bxg4 {[%emt 00:14:05]} hxg4 {[%emt 00:00:12]} 19.g3 {[%emt 00:00:04]} Rad8 {[%emt 00:41:27]} 20.Rxd8 {[%emt 00:00:13]} Kxd8 {[%emt 00:00:06]} 21.Rh1 {[%emt 00:07:39]} Ke7 {[%emt 00:04:24]} 22.Kd2 {[%emt 00:00:25]} b6 {[%emt 00:03:39]} 23.Nd1 {[%emt 00:07:39]} a4 {[%emt 00:05:32]} 24.Nf2 {[%emt 00:02:23]} axb3 {[%emt 00:02:05]} 25.axb3 {[%emt 00:00:05]} Ra8 {[%emt 00:00:52]} 26.h5 {[%emt 00:04:54]} Ra2+ {[%emt 00:03:09]} 27.Ke3 {[%emt 00:00:04]} gxh5 {[%emt 00:00:41]} 28.Rxh5 {[%emt 00:00:05]} Rb2 {[%emt 00:00:12]} 29.Nxg4 {[%emt 00:00:57]} Rxb3+ {[%emt 00:00:07]} 30.Kf2 {[%emt 00:00:07]} Rb2+ {[%emt 00:00:29]} 31.Kf1 {[%emt 00:17:19]} Rb1+ {[%emt 00:00:35]} 32.Ke2 {[%emt 00:00:27]} Rb2+ {[%emt 00:01:16]} 33.Kf3 {[%emt 00:04:28]} Rb3+ {[%emt 00:00:26]} 34.Kg2 {[%emt 00:00:20]} Rb2+ {[%emt 00:00:29]} 35.Kh3 {[%emt 00:00:04]} Rb1 {[%emt 00:01:02]} 36.Rf5 {[%emt 00:00:15]} Nd6 {[%emt 00:04:56]} 37.Rxf6 {[%emt 00:00:06]} Nxe4 {[%emt 00:00:06]} 38.Rg6 {[%emt 00:05:25]} Rh1+ {[%emt 00:07:15]} 39.Kg2 {[%emt 00:00:09]} Rc1 {[%emt 00:00:08]} 40.Ne5 {[%emt 00:01:17]} Rc2+ {[%emt 00:11:41]} 41.Kh3 {[%emt 00:00:40]} c5 {[%emt 00:05:56]} 42.Kg4 {[%emt 00:09:05]} Nd6 {[%emt 00:09:05]} 43.f5 {[%emt 00:16:40]} Nxc4 {[%emt 00:10:20]} 44.Re6+ {[%emt 00:02:10]} Kd8 {[%emt 00:02:44]} 45.Nxc4 {[%emt 00:02:49]} Rxc4+ {[%emt 00:00:06]} 46.Kg5 {[%emt 00:00:03]} Rc3 {[%emt 00:08:37]} 47.g4 {[%emt 00:00:09]} c4 {[%emt 00:00:47]} 48.Kf6 {[%emt 00:06:51]} Rg3 {[%emt 00:01:53]} 49.g5 {[%emt 00:00:32]} c3 {[%emt 00:02:24]} 50.g6 {[%emt 00:02:12]} b5 {[%emt 00:00:48]} 51.g7 {[%emt 00:05:26]} b4 {[%emt 00:01:47]} 52.Kf7 {[%emt 00:01:47]} Rxg7+ {[%emt 00:05:44]} 53.Kxg7 {[%emt 00:00:04]} c2 {[%emt 00:00:08]} 54.Re1 {[%emt 00:00:10]} b3 {[%emt 00:00:03]} 55.f6 {[%emt 00:00:04]} b2 {[%emt 00:00:04]} 56.f7 {[%emt 00:00:03]} c1Q {[%emt 00:02:21]} 57.f8Q+ {[%emt 00:00:12]} Kd7 {[%emt 00:00:05]} 58.Qf5+ {[%emt 00:00:20]} 1-0

**Comment by gbtami** [comment]
Maybe the first tag should be Event and ePGN should be placed after the seven mandatory tags.
See http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c8.1.1

**Comment by mliebelt** [comment]
I use usually the [Configuration Builder](https://mliebelt.github.io/PgnViewerJS/docu/example/config.html) for that purpose. With a little bit fiddling, I found the following

`56.f7 {[%emt 00:00:03]} c1=Q {[%emt 00:02:21]} 57.f8=Q+ {[%emt 00:00:12]}` works
but `56.f7 {[%emt 00:00:03]} c1Q {[%emt 00:02:21]} 57.f8Q+ {[%emt 00:00:12]}` does not.

See the [PGN specification](http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c8.2.3) chapter 8.2.3.3

> Pawn promotions are denoted by the equal sign "=" immediately following the destination square with a promoted piece letter (indicating one of knight, bishop, rook, or queen) immediately following the equal sign. As above, the piece letter is in upper case.
