### ISSUE TITLE
Setup/FEN in the PGN is not recognized

### ISSUE THREAD

**Issue by gcp** [mliebelt/PgnViewerJS#129]
```
[Event "CT Tactics Problem"]
[Site "chesstempo.com"]
[White "Thomas Luther"]
[Black "Vladamir Malaniuk"]
[Date "1991"]
[Result "0-1"]
[FEN "3r2k1/2rP1pp1/2q4p/2N5/7Q/4P2P/6P1/3R2K1 b - - 5 38"]

38. .. g5 
39. Qe4 Qxc5 
40. Qe8 Qf8
```

Even if a ```[SetUp "1"]``` tag is added, the parser breaks because it doesn't handle the FEN tag. I guess as a workaround I could try to manually extract those and feed them to ```position```.

**Comment by gcp** [comment]
Note that even fixing the ```...``` on move 38 does not resolve this.

**Comment by gcp** [comment]
Even if the FEN is extracted and fed as ```position```, it gets confused because black is to move and it doesn't expect the moves to start with ```. ..```.

**Comment by mliebelt** [comment]
After fixing the (wrong) move number `38. .. g5`, and adding the tag `[SetUp "1"]` the example was working. Try it at http://mliebelt.github.io/PgnViewerJS/docu/example/config.html with the following example:

```
[Event "CT Tactics Problem"]
[Site "chesstempo.com"]
[White "Thomas Luther"]
[Black "Vladamir Malaniuk"]
[Date "1991"]
[Result "0-1"]
[FEN "3r2k1/2rP1pp1/2q4p/2N5/7Q/4P2P/6P1/3R2K1 b - - 5 38"]
[SetUp "1"]

38... g5 
39. Qe4 Qxc5 
40. Qe8 Qf8
```
After fixing #130 `38. ..` will work as well.

**Comment by mliebelt** [comment]
Is it ok to close this ticket? At least the PgnViewerJS behaves like described in http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c9.7

**Comment by gcp** [comment]
Sounds good.
