### ISSUE TITLE
FEN with black position is not recognized as that

### ISSUE THREAD

**Issue by mliebelt** [mliebelt/PgnViewerJS#13]
The following issue was entered by calvicius as a comment to another issue. Because it seems to be a different problem, I have added a separate issue for it. I hope I have got the intention right, 

---

I have a problem with fen positions
Your edit.html example 
originaly inits with position:'start'. So ... if I change the start position with a fen with side to move as black; lets say : position : 'rnbqkbnr/pp1p1ppp/4p3/4P3/2PQ4/2N5/PP3PPP/R1B1KBNR b KQkq - 0 6' always inittiates the process as white to move.

I have also tried to change in html like this : 

``` javascript
    <script id="identificador_js" cadena="<?echo $cadena1; ?>" src="../js/pgnvjs.js"                          type="text/javascript">
```

and then change pgnvjs like this

``` javascript
//recuperamos la query string
var locojo=document.getElementById('identificador_js');
var esmio=locojo.getAttribute('cadena');
```

for receiving the fen chain, then I have changed this (ten lines below):

`//var game = new Chess();`
to
`var game = new Chess(esmio); with "'"+esmio+"'" also`

and the problem persists.

**Comment by mliebelt** [comment]
I will try to reproduce your problem in an example, and then try to find the reason for it. FEN has the information which color has to move, I don't remember, if I have used that information.

**Comment by calvicius** [comment]
thanks for your interest.
I think to remember that chessboardjs didn't ocupate about the sides and castles, so it only treats with fen shorted like "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR" type nor abot w or b, nor KQkq.

I detail below a short code made for my own use in wich var game_new Chess()  receives a FEN from an input form, and then it will be treated for emscripten stockfish :
quote
<?php
$cadena1 = $_POST['posicion'];
$cadena1 = "'".$cadena1."'";
echo $cadena1;
?>

<!doctype html>
<html>
<head>
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/chessboard-0.3.0.min.css" />
    <script src="js/jquery-1.10.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/chess.min.js"></script>
    <script src="js/chessboard-0.3.0.min.js"></script>
    <title>Motor Calvicius</title>
</head>
<body>

<div id="board" style="width: 300px; margin: 5px;"></div>
<p>&nbsp;&nbsp;Status: <span id="status" style="margin: 5px;"></span></p>
<p>&nbsp;&nbsp;FEN: <span id="fen" style="margin: 5px;"></span></p>
<p>&nbsp;&nbsp;PGN: <span id="pgn" style="margin: 5px;"></span></p>

<script>
var board,
  game = new Chess(<?php echo $cadena1; ?>),   //antes era new Chess(),
  statusEl = $('#status'),
  fenEl = $('#fen'),
  pgnEl = $('#pgn'); 


// do not pick up pieces if the game is over
// only pick up pieces for the side to move
var onDragStart = function(source, piece, position, orientation) {
  if (game.game_over() === true ||
      (game.turn() === 'w' && piece.search(/^b/) !== -1) ||
      (game.turn() === 'b' && piece.search(/^w/) !== -1)) {
    return false;
  }
};

var onDrop = function(source, target) {
  // see if the move is legal
  var move = game.move({
    from: source,
    to: target,
    promotion: 'q' // NOTE: always promote to a queen for example simplicity
  });

  // illegal move
  if (move === null) return 'snapback';

  updateStatus();
};

// update the board position after the piece snap 
// for castling, en passant, pawn promotion
var onSnapEnd = function() {
  board.position(game.fen());
};

var updateStatus = function() {
  var status = '';

  var moveColor = 'Blancas';
  if (game.turn() === 'b') {
    moveColor = 'Negras';
  }

  // checkmate?
  if (game.in_checkmate() === true) {
    status = 'Game over, ' + moveColor + ' is in checkmate.';
  }

  // draw?
  else if (game.in_draw() === true) {
    status = 'Game over, drawn position';
  }

  // game still on
  else {
    status = moveColor + ' juegan';

    // check?
    if (game.in_check() === true) {
      status += ', ' + moveColor + ' is in check';
    }
  }

  statusEl.html(status);
  fenEl.html(game.fen());
  pgnEl.html(game.pgn());
};

var cfg = {
  showNotation: false,
  draggable: true,
  position: <?php echo $cadena1; ?>,   //antes era position: 'start',
  onDragStart: onDragStart,
  onDrop: onDrop,
  onSnapEnd: onSnapEnd,
  pieceTheme: 'img/chesspieces/wikipedia/{piece}.png',
};
board = ChessBoard('board', cfg);

updateStatus();

</script>

<div id="mensaje" style="margin: 5px; color: #D84F4B; font-size: 16px;"></div>
	<TEXTAREA COLS=100 ROWS=5 NAME="AreaMotor" id="AreaMotor" value=" " style="overflow:auto;border:solid 1px black; margin: 5px;" >
		
	</TEXTAREA>


<p></p>
<input class="btn btn-danger" type="button" id="LanzaMotorBtn" value="Lanza el motor" style="margin: 5px;">
<script>
		var linea_area = "";

		function clickLanzaMotorBtn() {
			document.getElementById("AreaMotor").value = " ";   //vaciamos la text area para cada nuevo analisis
			var mensaje = document.querySelector("#mensaje");
			var motor ='js/stockfish.js';
			var stockfish = new Worker(motor);
			stockfish.onmessage = function(event) { 
				console.log(event.data); 
			};
			posic_motor = 'position fen ' + game.fen();
			// sotckfish.postMessage('uci');  <!--esto solo sale en console.log y solo salen los programadores
			// stockfish.postMessage('setoption name Hash value 128');  //<-- el asm.js casca con el emscripten
			// stockfish.postMessage('setoption name Threads value 1');  <--- el emscripten nada mas permite un hilo
			// stockfish.postMessage('setmultipv 2');  <--el emscripten nada mas da la mejor jugada
			//stockfish.postMessage('uci');
			stockfish.postMessage(posic_motor);
			stockfish.postMessage('go depth 20');
	  
			stockfish.onmessage = function(event) {
				//NOTA: los Web Workers meten la respuesta en un objeto.
				//console.log(event.data ? event.data : event);
				//mensaje.innerHTML = "<INS>Mejor jugada</INS>&nbsp;&nbsp;&nbsp;<INS>Mejor replica</INS>" + "<p></p>" + (event.data ? event.data : event) +"\r\n";
				var linea_analisis = event.data;
				linea = linea_analisis.replace(/\r?\n/g, "<br>");  //intento cambiar el salto de linea final por <br> pero no funciona
				//$("#mensaje").html("<pre><br>" + linea_analisis + "</pre>");
				$("#mensaje").html(linea);
				linea_area = linea_area + linea_analisis + "\n";
				//mensaje.innerHTML = "<INS>Mejor jugada</INS>&nbsp;&nbsp;&nbsp;<INS>Mejor replica</INS>" + "<p></p>" + linea;
				document.getElementById("AreaMotor").value = linea_area;
			};
		}
		$('#LanzaMotorBtn').on('click', clickLanzaMotorBtn);
    </script>
</body>
unquote

**Comment by mliebelt** [comment]
I have reproduced your problem, but I have no fix yet. I have added the gist https://gist.github.com/mliebelt/139d3cdff816160e1e0c that contains two examples that should both work, one with only viewing games, the other for editing games. As you can see there, starting not from the initial position is currently not supported at all, but should be. It is possible to create a board (`pgnBoard`) with a different position, and this works equally well with setting up `pgnView` and `pgnEdit`. However, making moves not from the initial position (where white should start) is not supported. So I have to fix that first ...

**Comment by mliebelt** [comment]
See the [example as part of the documentation](http://mliebelt.github.io/PgnViewerJS/docu/examples2.html#1209) how to use it. When you hover withe the mouse over the black pieces, you see that only the black pieces are allowed to move here.

**Comment by mliebelt** [comment]
Seems to be a bug again, have to have a look, what the problem is. The symptom is the following:

- Have a FEN string with black to move.
- Use edit mode.
- Then you are able to play the defined moves, but are not able to start new ones.
