### ISSUE TITLE
RAV parsing problem

### ISSUE THREAD

**Issue by gcp** [mliebelt/PgnViewerJS#130]
```
[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "?"]
[Black "?"]
[Result "*"]

1.d4 d5 2.c4 e5 3.dxe5 d4 4.e3 Bb4+ 5.Bd2 dxe3 6.Bxb4 $4 exf2+ 7.Ke2 
    ( 7.Kxf2 Qxd1 )
7. .. fxg1=N+ 
    ( 7. .. fxg1=Q 8.Qxd8+ Kxd8 9.Rxg1 )
8.Rxg1 Bg4+ *
```

Parsing fails.

**Comment by gcp** [comment]
Other example:

```
[Event "Mumbai Wealth Open 3rd"]
[Site "Mumbai IND"]
[Date "2018.01.05"]
[Round "7"]
[White "Khusenkhojaev, Muhammad"]
[Black "Atalik, Suat"]
[Result "1/2-1/2"]
[WhiteElo "2451"]
[BlackElo "2545"]
[ECO "D85r"]
[EventDate "2017.12.30"]
[Annotator "Atalik,S"]
[EventType "swiss"]
[EventRounds "9"]
[EventCountry "IND"]

1.d4 Nf6 2.c4 g6 3.Nc3 d5 4.cxd5 Nxd5 5.e4 Nxc3 6.bxc3 Bg7 7.Nf3 c5 8.Rb1 O-O 9.Be2 cxd4 10.cxd4 Qa5+ 11.Bd2 Qxa2 12.O-O b6 $5 
    {An old line.}
13.Qc1 
    ( 13.Bg5 Bb7 14.Bd3 Qe6 15.Re1 Qd6 {Miladinovic,I-Atalik,S,Vrnjacka Banja 1992.} )
13...Bb7 14.Bc4 Qa4 15.Bb5 Qa2 16.Bc4 
    ( 16.Re1 Rc8 17.Qd1 Qc2 18.Qe2 Nc6 19.Bd3 Qa2 20.Bc4 Qa4 
        ( 20...Qa3 $2 21.Bxf7+ $1 )
    21.Bb5 
        ( 21.Ra1 Qc2 22.Bd3 Qb2 23.Ra4 b5 $1 24.Bxb5 a5 $1 $132 )
    21...Qc2 $11 )
16...Qa4 17.Bb5 Qa2 18.Bc4 Qa4 1/2-1/2
```

**Comment by gcp** [comment]
The text has Zero Width Spaces in them. I can filter that.

**Comment by gcp** [comment]
Reopened - the second example was a red herring, but I think this input is correct (yet fails to be parsed).

**Comment by mliebelt** [comment]
The reason for that is the following section in the PGN specification:

> 8.2.2.1: Import format move number indications
PGN import format does not require move number indications. It does not prohibit superfluous move number indications anywhere in the movetext as long as the move numbers are correct.

> PGN import format move number indications may have zero or more period characters following the digit sequence that gives the move number; one or more white space characters may appear between the digit sequence and the period(s).

So the parser could here be a little bit more robust, by allowing any number of white space and dots after the move number.

This is the current rule used:

```
moveNumber
    = num:integer"."? { return num; }
```

I think this should be fixable. And yes, the part `7. .. fxg1=Q` with the space between the dots was the reason.

**Comment by mliebelt** [comment]
This fix is only contained in the sources, and I will need some time to create a new version. I will keep the bug open as long as the fixed grammar is not contained in the dist-part of PgnViewerJS.

**Comment by gcp** [comment]
Thanks for fixing this.
