### ISSUE TITLE
CSS class rules aren't namespaced

### ISSUE THREAD

**Issue by gcp** [mliebelt/PgnViewerJS#131]
The used CSS uses many class names without any kind of namespacing or prefixing, i.e.: ```comment afterComment move white```.

This will cause clashes when integrating into existing sites, especially if those also did not namespace properly. (In my case, the old reddit layout also uses "comment". They fixed it in the new layout, but people still use the old one...)

**Comment by mliebelt** [comment]
I think I understand the point, and I had myself problems from here to there with common used class names (e.g. in the context of wordpress with it myriads of themes. I will try to address the ones that hurt most, this should be mostly a copy-paste action.

**Comment by mliebelt** [comment]
I have currently a top class named `whole` (not the best name, something like `pgnvjs` or so would be better).

I will try to do the following:

* Choose a better class for the surrounding div, set automatically.
* Make all CSS dependent on that class (at least).

This should avoid clashes by other layout systems, if possible
