### ISSUE TITLE
Unexpected scrolling after a move is played

### ISSUE THREAD

**Issue by jensguballa** [mliebelt/PgnViewerJS#136]
On a long page which does not fit completely in the browser window, and where the chess board is not at the top of the page, the complete page is scrolled up after each move.

The cause seems to be located in the function scrollToView, as after 
`var movesNode = node.offsetParent;`
`movesNode` points to the document body instead of the notation-div.

Replacing this by `var movesNode = node.parentElement;` resolved the issue and as expected only the notation is scrolled to make the current move visible.

**Comment by mliebelt** [comment]
Thank you for reporting that behavior. I will give it a try, and include it some time soon. I have to check first for different layouts if it behaves reliable.

**Comment by mliebelt** [comment]
Fixed that as well in the last commit, forgot the ticket number.
