### ISSUE TITLE
JavaScript error after last move

### ISSUE THREAD

**Issue by jensguballa** [mliebelt/PgnViewerJS#139]
If the last move of a game or a variant has been played, then trying to execute the next move causes an error in the console:
```
TypeError: that.mypgn.getMove(...) is undefined4 pgnvjs.js:13694:38
    nextMove http://grav.localhost/user/plugins/pgnviewerjs/assets/js/pgnvjs.js:13694
    bindFunctions http://grav.localhost/user/plugins/pgnviewerjs/assets/js/pgnvjs.js:13725
```
The error also occurs when using the autoplay button and the end of a variation is reached.

**Comment by mliebelt** [comment]
I will check that, should be easy to avoid. In former times, that next move thing avoided that, but that broke some  time. Being in the console is ok, so the error is not popping up to the user.
