### ISSUE TITLE
Move number missing for first black move

### ISSUE THREAD

**Issue by jensguballa** [mliebelt/PgnViewerJS#140]
If a PGN with an alternative starting position is provided and it is black to move, then the move number for this move is missing. This can be checked with the PGN mentioned in #138.

The first move is `Qe4` instead of the expected `63... Qe4`. It looks like only the main variant is affected.

**Comment by mliebelt** [comment]
I will check that. Should be easy to do that. I have to check as well, that something like

`1... e5 2. Nf3 Nc6 (2... d5 3. exd5) 3. Bc4 (3. Nc3) 3... Bc5` 

is working as well. So not only at the beginning of main line, but also all the time at the beginning of a variant, and at the new beginning of a main line after finishing a variant is working.

Thank's for the hint.

**Comment by mliebelt** [comment]
Now the first move gets all the time a move number.
