### ISSUE TITLE
Configuration for coordsInner and coordsFactor broken

### ISSUE THREAD

**Issue by jensguballa** [mliebelt/PgnViewerJS#141]
It seems that some configuration functionality is broken, e.g. "coordsInner" and "coordsFactor" are not configurable anymore. The configurator can be used to check this. I am not sure though if other configuration options are affected as well.

**Comment by mliebelt** [comment]
Checked the difference in Chessground (old and new), and found a change in class there. By following it, and hiding the fixed size of coordinates again, everything was as before.

**Comment by jensguballa** [comment]
Thank you quite a lot for the quick fix!
