### ISSUE TITLE
Locale not considered for promoted pieces

### ISSUE THREAD

**Issue by jensguballa** [mliebelt/PgnViewerJS#144]
When setting the locale to `de` and using the following PGN, the fifth move is displayed as `5. exf8=R`. Using the configuration builder the behavior is different: there the move is displayed as `5. exf8=R=T` (which makes me guess that in principle the locale is somehow already considered for promotees).

PGN:
```
[Event ""]
[Site ""]
[Date "????.??.??"]
[Round ""]
[White ""]
[Black ""]
[Result "*"]

1. h4 g5 2. hxg5 Nf6 3. gxf6 d6 4. fxe7 Kd7 5. exf8=R Qh4 6. Rxh8 Qxh1 7. Rxh7 Ke8 8. Rxh1 * 
```

**Comment by mliebelt** [comment]
Thank's for filing that bug, I have to add that to the suite of test cases that should run all the time.

**Comment by mliebelt** [comment]
i think the reason was different. A special case (pawn promotion, striking) led to a double output of promotion, first in PGN, second with tne internationalization. Should be fixed now.
