### ISSUE TITLE
Board bugged when generated inside of a details tag

### ISSUE THREAD

**Issue by ArneVogel** [mliebelt/PgnViewerJS#145]
When I generate a board inside a details tag the pieces are all smushed into a8. 

Bug in action: https://taktikspiel.com/tactics/magnus-carlsen-invitational/ (click Solution)

**Comment by mliebelt** [comment]
Hi @ArneVogel  nice to see my viewer used somewhere :-)

Can you provide the context here? I see it is broken, but how to construct a (bad) example that behaves like that? So something like:

    pgn = '1. ...';
    pgnView('b', {pgn: pgn, ...};

The reason here is that I want to be sure to have a minimal example for every bug, so I understand the problem correct. I don't get the meaning of "details tag" here. Could you provide an abstracted source of that?

**Comment by ArneVogel** [comment]
Hi @mliebelt thanks for the awesome library :)

Information about the details tag: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

---

A minimal example of the behavior inside of a details tag:
```
<details>
    <div id='testing'></div>
    <script>
        pgnBoard('testing',{ pgn: '1.e4', theme: 'zeit', pieceStyle: 'merida' });
    </script>
</details>
```
---
I was also table to reproduce the same behavior with:
```
<div id="testing2"></div>
<script>
    document.getElementById("testing2").style.display = "none";
    pgnBoard('testing2',{ pgn: '1.e4', theme: 'zeit', pieceStyle: 'merida' });
</script>
```
and making it visible manually later again with `document.getElementById("testing2").style.display = "block";`

---

Curiously this does not reproduce the bug
```

<div id="testing3"></div>
<script>
    document.getElementById("testing2").style.display = "none";
    pgnBoard('testing3',{ pgn: '1.e4', theme: 'zeit', pieceStyle: 'merida' });
    document.getElementById("testing2").style.display = "block";
</script>
```

**Comment by mliebelt** [comment]
Thank's for providing that example, I will see if I can reproduce the bug with the Chessground only (which is the implementation of the board), to see if the bug is there. Perhaps there will be a workaround available to have the board "refreshed" later. But this will need time ...

**Comment by mliebelt** [comment]
I have started investigating what the reason could be. The following gives the same result (without using PgnViewerJS at all).

    <details>
      <div id='testing'></div>
      <script>
          let my_div = document.getElementById("testing")
          window.Chessground(my_div, {})
      </script>
    </details>

So I will concentrate on the way to update the chess board at the right time. The board is not visible, when it is build, so the DOM does not have enough information to build it correctly.

**Comment by mliebelt** [comment]
I have found the reason for it, or at least a workaround. Here is the code for the Chessground only example.

    <details id="details">
        <div id='testing'></div>
    </details>
    
    <script>
        let my_div = document.getElementById("testing")
        let cg = window.Chessground(my_div, {})
        let details = document.getElementById("details")
        details.addEventListener("toggle", event => {
            if (details.open) {
                cg.redrawAll()
            } else {
                /* the element was toggled closed */
            }
        });
    </script>

I tried to use the same pattern for PgnViewerJS, but failed. I have first to fix the schedule part, to allow me to return something usefull from the call of pgnView, pgnEdit, pgnPrint and pgnBoard. This has to be a pre-requisit of this.

**Comment by mliebelt** [comment]
So I changed the base functions, to return something useful (see #146 ), so this implementation is now possible:

     <details id="details">
       <div id='testing2'></div>
     </details>

     <script>
        let pgnb = pgnBoard('testing2',{ pgn: '1.e4', theme: 'zeit', pieceStyle: 'merida' });
        let details = document.getElementById("details")
        details.addEventListener("toggle", event => {
            if (details.open) {
                pgnb.board.redrawAll()
            } else {
                /* the element was toggled closed */
            }
        });
    </script>

If you have an idea how to do that for any context without the manual callback, feel free to give me a hint on that.

**Comment by ArneVogel** [comment]
Thanks, the solution with redrawing the board works.

To avoid the manual callback I would assume the library could redraw automatically when the size of the containing div is changed. Some quick research suggests that there is no trivial way to trigger on a resize of a div so I am not sure if that is easily possible.

**Comment by mliebelt** [comment]
So I leave that closed, because the workaround is "good enough". If later, someone has a bright idea how to handle the "right" event, I could include that. I just want to avoid any clutter that may be not necessary for most of the usages.
