### ISSUE TITLE
The board is not showing the pieces or the squares

### ISSUE THREAD

**Issue by Everjg** [mliebelt/PgnViewerJS#169]
Hey @mliebelt, 

Thank you very much for your fantastic work! 

I've been getting this issue, after installing the PgnViewerjs

![Captura](https://user-images.githubusercontent.com/69699780/90305091-c3346500-de8c-11ea-94db-9bac7c48cbcf.PNG)

And I don't have a clue of where the problem comes from.

Have you ever faced this problem? Do you have a solution? Is there something that I am missing here?

**Comment by Everjg** [comment]
I am using Laragon as a server, in windows 7 sp1, I am editing with visual studio code. And I haven't been able to pull it off with the last version of the board. Older versions work like a charm. But I don't see what's the problem.

**Comment by mliebelt** [comment]
Normally you can diagnose the problems with the developer tools in your browser. The latest version (did you get it by using NPM) includes the assets at a fixed location, and depending on your deployment, the location on you server will be different.

I had not the time to document if in a good way. You should use the following:
* Go into your HTML file, where you include the javascript library.
* Ensure that before that inclusion, the following code is run: `__globalCustomDomain = '/wp-content/plugins/PgnViewerJS-WP/js/'` (This is an example from the wordpress plugin that includes the library. You have to use of course a custom local name.)

So if you have the Javascript files under `/my/local/path`, and this includes the directory `pgnv-assets`, the path should be: `__globalCustomDomain = '/my/local/path/'`.

I hope this fixes your problem.

**Comment by Everjg** [comment]
Thank you very much for your answer, it works!  I was going crazy with this error.

You're a genius! Again, I can't thank you enough.

**Comment by mliebelt** [comment]
Thank you for the timely reply, and thank you for the congratulations! I will try to add a section to the `README.md` that explains different deploy scenarios. What i forgot The repository https://github.com/mliebelt/example-webpack-dynamic-resources explains the whole context in detail an gives some examples.

**Comment by mliebelt** [comment]
I changed the deployment, now are all assets included in the javascript file. So everything should work out of the box, without any tweaking. I pushed the version 1.4.4 to NPM as well, should be available there soon.
