### ISSUE TITLE
Finish edit mode

### ISSUE THREAD

**Issue by mliebelt** [mliebelt/PgnViewerJS#17]
Currently the edit mode is nearly finished. The only things that are lacking:
- Some cleanup of the UI ( it is pretty ugly ). Use instead some of the nice icons from Font Awesome.
- Allow to cut variations and / or main lines.
- Allow to promote variations:
  - When you have 3 variations, you may promote the third, so it becomes the second.
  - When you promote the first variation, it becomes the main line.

**Comment by pawnflakes** [comment]
Hi

Thanks for a great pgn viewer! 

Any idea when this will be completed?

**Comment by mliebelt** [comment]
No, not really (sorry for that). My main work is taken all the time, so I was only able to do smaller things in the last months. But thank's for the feedback, that will motivate to invest some more time.

**Comment by mliebelt** [comment]
Finished edit mode, should be now feature complete
