### ISSUE TITLE
How can I identify the variables responsible for arrows and circles

### ISSUE THREAD

**Issue by Everjg** [mliebelt/PgnViewerJS#173]
Hey there!

I'd like to save the vectors of arrows, the coordinates of circles and their colors in my database, I am not sure about how does that work in the code.

Do you know how to get such data?  what variables are responsible for arrows, circles and their colors?

Thank you in advance, keep the good work!

**Comment by mliebelt** [comment]
I have just used the implementation done by Chessground, and they save the arrows and circles as structured comments. See the ticket #91 for that feature, and [the example file](https://github.com/mliebelt/PgnViewerJS/blob/master/modules/pgn-viewer/examples/tickets/ticket091.html) that shows how it works.

Here is the data I know (from the example comment `[%csl Bb7,Gf3,Gd4,Rh3,Rf2,Yc2,Yb2,Ba1,Be1][%cal Ge7e5,Gc7c5,Rb8c6,Rh7h5,Ba7a6,Yb7b5]`)

* Arrows and circles have their own comments.
* Arrows start with `%csl`, and contain then lists of color-coordinated.
* Colors available at the moment are: B - blue; G - green; R - red, Y - yellow.
* Coordinates for circles: just the line - row as usual.
* Arrows go: from - to

In Chessground, I found the following:

* API: https://github.com/ornicar/chessground/blob/0d33540ebc4af7f3f76dad44e5935396d8abf6a6/src/api.ts#L61 (setShapes)
* Brushes: https://github.com/ornicar/chessground/blob/ba9fda820e37f2a22c95be926f3a9cc74a943e27/src/state.ts#L167 seem to define the colors, line width, ... and there is the option to add others as well. So you could define your own brushes (color lineWidth) yourself, or overwrite the existing ones.

There is no API currently by PgnViewerJS to do that. There may be a way to access Chessground somehow. Or you could add the right configuration to your call, that is then copied to the boardConfiguration. But I think you will have to change sources to do that.

I hope that answer clarifies a little bit how the shapes of Chessground work.

**Comment by mliebelt** [comment]
I think I have answered that question, can we close it then? Or do you think there should be a feature that allows you to define the colors to use in showing something. The definition of circles and arrows is already defined, there could be only a variant how heavy they should be.
