### ISSUE TITLE
Give useful return value for calling the base functions

### ISSUE THREAD

**Issue by mliebelt** [mliebelt/PgnViewerJS#174]
When calling the base functions `pgnView`, `pgnEdit`, `pgnBoard` and `pgnPrint`, there was in the past a value returned (see [return value of pgnBase](https://github.com/mliebelt/PgnViewerJS/blob/750b6724fe0d46f4f46bd8c9ab5ebd2f6c77d0e5/modules/pgn-viewer/src/pgnvjs.js#L1270)). By introducing lazy loading of internationalization labels (i18n) in a lazy way, this return value got lost.

By having one object returned again, there may be other features possible, that are now not possible to implement.

**Comment by jvsteiner** [comment]
I figured it out.

The problem is here:

```
GLOB_SCHED.schedule = function (loc, func) {
    let my_res = null;
    let myLoc = (typeof loc != 'undefined') ? loc : 'en';
    if (i18next.hasResourceBundle(myLoc)) {
        my_res = func.call(null);
    } else {
        i18next.loadLanguages(myLoc, (err, t) => {  // <- loadLanguages returns a Promise
            my_res = func.call(null);
            console.log("my_res upon promise resolution", my_res);
        });
    }
    console.log("my_res upon function return", my_res);
    return my_res;
};
```
if you add these log lines and instantiate a pgnEdit like this:

```
let pgnv = PGNV.pgnEdit('b1', {pgn: ""});
console.log("pgnv", pgnv);
```
you will see the order of logging like this:

```
my_res upon function return null
pgnv null
my_res upon promise resolution {base: {…}, board: {…}}
```
So you either have to await that promise, or move the call to `func` outside the scope of the call of the `loadLanguages` callback.  I recommend the latter, which would look like:

```
    } else {
        i18next.loadLanguages(myLoc);
        my_res = func.call(null);
    }
```

**Comment by mliebelt** [comment]
Checked it the whole evening, and your analysis helped somehow, but not complete. The only way to have i18next working, and have a return value is to keep the promises. I have now a working example, where I can access parts of the viewer, so if that viewer had a useful API, I would be able to use it.

Looks a little bit ugly at the moment, and I am not sure, what that does that with the whole idea. Perhaps tomorrow!

Thank you a lot for participating here, this helps really.

**Comment by jvsteiner** [comment]
I also experimented with awaiting the promise.  I will admit that I am not really too familiar with js promises (usually I am writing backend code in golang, where the mental model of concurrency is very different) but my experiments resulted in me making a lot of functions `async` and then writing more functions to await them.  I learned that this approach doesn't really lead to any solution, since the `await` keyword blocks only within the functions scope - basically when you get there, execution shifts to another part of the code.

Normally functions that execute this way are intended to work such that their effects will work, even if they do not block.  Why doesn't i18next work if you do not await?  maybe you would push some branch to look at?

**Comment by mliebelt** [comment]
I pushed a first version on the branch. I changed the following:

* Did an example that shows how to get access to the viewer. See [sources](https://github.com/mliebelt/PgnViewerJS/blob/ticket-174/modules/pgn-viewer/examples/modes/edit/layout-left.html)
* The schedule method now returns the promise. So after the loading of locale data is finished, you can then use promise.then( ,<func> ) to do something inside the function.
* By binding the value of that promise to `PGNV.currentPGN`, I was then able inside the console to do calls like `PGNV.currentPGN.base.manualMove('e4')`. This should work the same way with the edit mode.

I am not yet glad with that version, because it seems to be cumbersome. So I will think again, if there are other possibilities easier to use.

**Comment by mliebelt** [comment]
I checked if there are other possibilities available, tried for that reason the following:

* https://i18njs.com/ (see https://www.npmjs.com/package/roddeh-i18n for NPM): Small library, easy to use, but no support for download of files. When doing fetch in the browser, there are the promises again.
* https://www.npmjs.com/package/i18n Interesting library, but for server side. I found even https://github.com/romainbessugesmeusy/gulp-i18n-static that tries to do something similar, but is overkill (in my opinion).

So the problem seems to be a hard one. I see currently different solutions (additional to the one already implemented):

* Define the internationalization texts inside the Javascript library, to avoid the load of data.
* Provide custom builds that only use some of the locales, to avoid bloat of the library. (There was never ever anyone asking for internationalization, but I want to have at least German (additional to English) working.)

Will do some experiments with that as well.

**Comment by jvsteiner** [comment]
While experimenting with running stockfish engine in the browser, I discovered that, coincidentally, the API is similar in that you have to put the main code you want to run inside a `then()` function.  It's not actually that bad.  What looks like:

```
let pgnv = PGNV.pgnBase(el, config);
// do stuff with pgnv
```
becomes
```
PGNV.pgnBase(el, config).then(pgnv => {
    // do same stuff with pgnv
});
```

At first I didn't like it, but upon reflection, maybe it's not so bad...

**Comment by mliebelt** [comment]
I may depend on what you want to do. To integrate the viewer into your own application may be cumbersome then, but you can get away with it. I will try the alternative, to have the key / values integrated during build. If that is doable, I will do that instead.

**Comment by jvsteiner** [comment]
> to have the key / values integrated during build

indeed, if possible, this would be better

**Comment by mliebelt** [comment]
This was already solved by using now a synchronous library to read locale values, and to inline those (no additional file for locale data during runtime). See the example referenced in #171
