### ISSUE TITLE
Allow users to change color of move text. 

### ISSUE THREAD

**Issue by trevor-ofarrell** [mliebelt/PgnViewerJS#196]
I was able to over ride the player name styles(need white text for a dark background), but was not able to override the move text color. It would be nice if you could choose the text color in the Pgnview function properties.

**Comment by mliebelt** [comment]
When you open the [configuration builder](https://mliebelt.github.io/PgnViewerJS/config/config.html), select there for Game "Evergreen (no boards)", you will see pgnView with some game in it.

In the developer tools, you have now the option to look on the CSS of the parts.

I don't see a difference here for player name styles and the moves styles. Both are defined only in CSS, and can be adjusted by one of the following:

* Add custom CSS and load that after `pgnv.js` (with CSS included). This should override the defaults of PgnViewerJS.
* Use some post function after loading a game, to set inline CSS for the elements.

The relevant elements are:

* Moves: `moves`
* White Header: class `whiteHeader`
* Black Header: class `blackHeader`

In using the developer tools of every browser, I am able to overwrite the styles, and see the effect directly.

Besides that, what should be the kind of configuration to do that? Any idea?

I could think of something like:

    config = {pgn: ..., cssStyles: {
        moves: "backgroundColor: 'black', color: 'white'",
        whiteHeader: ...,
        blackHeader: ... }
    }

Then I have to find a way to set those defined styles as inline styles for each element. I am not sure if that could be done in a generic way, but at least for the major 5-10 elements used, this could be possible.

**Comment by trevor-ofarrell** [comment]
I'm using PgnViewerJS in react so the way I'm trying to override the styles is through a class, and inline styles `import React, { useLayoutEffect } from 'react';
import * as uuid from 'uuid';
import Children from 'react-children-utilities';
import { pgnView } from '@mliebelt/pgn-viewer';
import { makeStyles, ThemeProvider } from '@material-ui/core/styles';

const useStyles = makeStyles((theme) => ({
  root: {
    color: [['white'], '!important'],
  },
}));

const PgnViewer = (props) => {
  const classes = useStyles();
  const gameDecription = Children.onlyText(props.children).replace(/ \{[\s\S]*?\}/g, '');
  const id = `board-${uuid.v4()}`;
  console.log(gameDecription);

  useLayoutEffect(() => {
    pgnView(id,
      {
        pgn: gameDecription,
        theme: 'brown',
        pieceStyle: 'wikipedia',
        timerTime: '1000',
        locale: 'pl',
        startPlay: 1,
        showResult: true,
        showFen: true,
      });
  });

  return (
    <div id={id} style={{ marginLeft: 'auto', marginRight: 'auto', color: 'white' }} className={classes.root} />
  );
};

export default PgnViewer;
`

This works to change the name color, but the moves color remains black.
![image](https://user-images.githubusercontent.com/47125174/111749918-b70fec00-884f-11eb-9759-95c1e045dad3.png)
It, could be something I'm missing but I have not found a way to apply styles to the moves. How would you add the custom css to load after the pgnviewer?

As for the config I was thinking something like this: `  useLayoutEffect(() => {
    pgnView(id,
      {
        pgn: gameDecription,
        theme: 'brown',
		moveColor: '#ffffff',
        pieceStyle: 'wikipedia',
        timerTime: '1000',
        locale: 'pl',
        startPlay: 1,
      });
  });`

But I like what you wrote, allows for more customizing.

**Comment by mliebelt** [comment]
I don't know react, so I can only speculate here. When I run the PgnViewer locally, I am able to modify the colors in the browser:

* `.whole { background: gray; color: white; }`
* `.moves { color: white; }`
* `.moves .comment { color: lightGray; }`

There may be more styles with explicitly set colors. By setting only the global one (`.whole`), the local rules about moves and comments are more specific. So you should be able to add that directly to your CSS to override the styles of PgnViewerJS.

**Comment by trevor-ofarrell** [comment]
That works great! Thank you. Nice solution. I'll go ahead and close this issue.
