### ISSUE TITLE
Clicking on a variation doesn't work (Firefox)

### ISSUE THREAD

**Issue by LocutusOfPenguin** [mliebelt/PgnViewerJS#20]
Hi,
in your examples, if i click on a move in a variation, the board doesn't update (correctly).
That is only working on the main line.

**Comment by LocutusOfPenguin** [comment]
Also in yr file pgnvjs.js i think there is an error at line 467 .. It should be:

`        moveSpan(currentCounter).on('click', function(evt) {
            makeMove(that.currentMove, currentCounter, move.fen);
            evt.stopPropagation();
        });`

**Comment by mliebelt** [comment]
Just to be sure that I understand your problem (clicking on variation) correct. I do the following:

- Go to the example http://mliebelt.github.io/PgnViewerJS/docu/examples2.html#1102
- Click on a move in the variation (have no URL for that). I have done it for
  - 1... c5 (first variation)
  - 3... cxd4 (first variation, 5th move)
  - 6... a6 (first first variation, some move)

I had no problems at all. How can I get your result? I am using a current Chrome browser. Tried some different browsers, no change.

**Comment by LocutusOfPenguin** [comment]
Hallo,

on chrome Version 51.0.2704.79 Ubuntu 16.04 (64-bit) it is working.
on firefox (47.0 also Ubuntu) its not

On FF, it always shows the var very shortly and then return to the last move of main line.


Agree with my last posting (JS-error)?
Jürgen

**Comment by mliebelt** [comment]
I could reproduce your problem with Firefox as well. The fix I found (sorry, no chance to make a quick fix) is the following:

      moveSpan(currentCounter).on('click', function(event) {
          makeMove(that.currentMove, currentCounter, move.fen);
          event.stopPropagation();
      });

So by adding the event parameter explicitly, Firefox now behaves as Chrome. So I hope you can introduce that into the distro yourself, I have no time at the moment to do a release, and a lot of changes in my current version.

Thank's a lot for reporting that error, I will try to fix it in the next weeks to come.

**Comment by LocutusOfPenguin** [comment]
Well, that what i posted already (see second post).
For me, this (our) fix solved the problem!


I found this project cause i'm looking for an alternative to the current (with flaws) webserver implementation to the project http://github.com/jromang/picochess.
But im still not sure, cause i have something similar as #19 .. Moves are made in backend, and needs to be reflected in frontend (=not a ended pgn-file). We have two use-cases. 1) Show finished pgn-files and 2) Show the ongoing game (for this im not sure as said above) and this is the main use for picochess webserver.
In this light i hope y can include this fix and the many other improvements in yr pipeline quickly :-)

**Comment by mliebelt** [comment]
Thanks for the correction, I didn't see the additional argument in your first hint.  I will try to come with a solution for #19 that allows to play games by the interface. See my comment there ...

**Comment by mliebelt** [comment]
Closed with the newest release
