### ISSUE TITLE
Result 1-0 & 0-1 inside the moves list leads to an error

### ISSUE THREAD

**Issue by LocutusOfPenguin** [mliebelt/PgnViewerJS#21]
I tried the following code:

    var pgn = '[Event "PicoChess game"]\
            [Site "?"]\
            [Date "2016.08.16"]\
            [Round "?"]\
            [White "Player"]\
            [Black "Stockfish 7 64 POPCNT"]\
            [Result "0-1"]\
            [SetUp "1"]\
            [FEN "rnbqkbnr/1ppppppp/p7/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2"]\
            2. Nc3 e5 3. Nf3 Qe7 4. Nd5 Qd8 5. Nxe5 Bc5 6. d4 Ba7 7. Bc4 h5 8. Nxf7 Qh4 9.\
            Nxc7+ Kf8 10. Qf3 g5 11. Bxg5 Qg4 12. Qxg4 hxg4 13. Nxh8 Bxd4 14. O-O-O Bxh8\
            15. Nxa8 d5 16. Rxd5 Nc6 17. Nc7 Nge7 18. Bh6+ Kg8 19. Rh5+ Be6 20. Bxe6+ Kh7\
            21. Bf8+ Kg6 1-0';

    var cfg = { position: 'rnbqkbnr/1ppppppp/p7/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2',
        pgn: pgn, locale: 'en', pieceStyle: 'merida' };
    var board = pgnView('board', cfg);

This leads to:
SyntaxError: Expected " ", ".", "O-O", "O-O-O", "x", "{", [RNBQK] or [a-h] but "-" found.
and not working...If i change the result to 1/2 or * it works.

**Comment by mliebelt** [comment]
I have removed the last paragraph and created the new issue #23 instead, to avoid that it will be overlooked later.

**Comment by mliebelt** [comment]
I have mistakenly used "1:0" and "0:1" as results and had that in the rules. I have added the rules for "1-0" and "0-1" as defined in the [pgn specification](http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm) (chapter 8.1.1.7). However it is not printed below the moves, just read from the parser.

**Comment by mliebelt** [comment]
Closed with the newest release.
