### ISSUE TITLE
orientation='black' does not switch player names

### ISSUE THREAD

**Issue by amahabal** [mliebelt/PgnViewerJS#234]
The white player's name seems to always be at the bottom even when the black pieces are at the bottom.

**Comment by mliebelt** [comment]
I tried to reproduce your error, but cannot. I did the following steps:

1. Went to https://mliebelt.github.io/PgnViewerJS/config/config.html
2. Selected from the dropdown Game "Evergreen (no boards)"
3. Enable Headers
4. I see now Anderssen as White and Dufresne as Black.
5. Pressing the button "Flip the sides of the board", the names are exchanged.

With the following order, I can reproduce it:
 1. Go to https://mliebelt.github.io/PgnViewerJS/config/config.html
 2. Deselect button Orientation (so Black is now at the bottom).
 3. Select from dropdown Games "Evergreen (no boards)"
 4. Anderssen is now shown at the bottom (Black), not at the top (White).

Thank you for creating that issue.

**Comment by mliebelt** [comment]
Fixed the problem, will only close the ticket when the next version is made available.
