### ISSUE TITLE
Fontawesome not loading

### ISSUE THREAD

**Issue by imprudenza** [mliebelt/PgnViewerJS#235]
Thank you for this awesome library, really useful!

Issue:
I use the libary to visualize a match on a webpage, in this page I normally use fontawesome, but if I include the js libraries every font awesome icon just disappear.

I think this is caused by a conflict, I have tried to import fontawesome both via webfont and via SVG (which just doesn't load any icon, but everything works) & JS (which load but the board control are broken). I have tried both with latest version of fontawesome and with 5.13.1 (which is used in your js library).

**Comment by mliebelt** [comment]
Could you please answer the following questions, so I could be able to reproduce your problem?

* What is the version of `pgn-viewer` you are using?
* Is the page public, so could I have a look at it?
* What is the order the libraries are imported?
* How is Fontawesome used? As link to CDN, as local library?

I have created yesterday a new version, that addressed a Fontawesome problem. Have you used that version 1.5.4?

**Comment by imprudenza** [comment]
- I am using v1.5.1 (the last one)
- Yes, the page is available clicking on the "Info" button on every match of the https://favo.ddns.net/matches.php page (for the view mode) and in the https://favo.ddns.net/analyse.php page (for the edit mode)
- I imported the libraries including them directly in the head tag
- I use the fontawesome's CDN, included in the head, before importing the libraries, but I have tried importing it also after, with the same result.


I will try right now the 1.5.4 library and let you know asap.

**Comment by imprudenza** [comment]
I am trying to install the new version using npm but I am having some problems:
I run the "npm i @mliebelt/pgn-viewer" command and the package gets downloaded, but when I build the package ("npm build") it just doens't do nothing.
The libraries doesn't get generated and the folder "lib/pgnv.js" doesn't exists resulting in a 404 error on my webpage.

The only way to get the working library is downloading the old version from github and importing it into the webserver, but the fontawesome icons are not working.

Any tip?

**Comment by mliebelt** [comment]
I had an error this afternoon when building a new version, so the javascript files were not included in the NPM version. But I was able to get the latest version 1.5.8, I just checked again using the following setup:

1. Create a new directory.
2. Do a `npm init` in it, with all defaults.
3. Include the following in `package.json`: `"dependencies": { "@mliebelt/pgn-viewer": "^1.5.8" }`.
4. Do an `npm install`.
5. Check the directory `node_modules/@mliebelt/pgn-viewer`.

The lib directory is there, with the relevant files.

Sorry for the inconvenience, I did not  noticed after building and publishing 1.5.7, only after an hour or so.

**Comment by imprudenza** [comment]
Thank you for your help, I was able to use the library (v1.5.8) but the fontawesome icons are still not working :(

I had another problem, the pieces are wrongly placed:

![image](https://user-images.githubusercontent.com/59796435/119274897-844cf000-bc12-11eb-93d0-c2d64c8db1a1.png)

Just flipping the side of the board with the first button below the chessboard fixes the problem.

**Comment by mliebelt** [comment]
Does that mean that I can close that ticket? I can see the chess icon from Fontawesome working, so seems to be fixed. Is it by accident that the moves are not shown? Reason is that layout==left with boardSize == width lead to no room left for moves. You may close the ticket as well, if it is done now.

**Comment by mliebelt** [comment]
I have added 2 examples that show different behavior in loading Fontawesome before or after PgnViewerJS.

* https://github.com/mliebelt/PgnViewerJS/blob/master/modules/pgn-viewer/examples/tickets/ticket235.html Shows the first screenshot below ✔️ 
* https://github.com/mliebelt/PgnViewerJS/blob/master/modules/pgn-viewer/examples/tickets/ticket235-2.html Shows the second screenshot, with the wrong icon (I think) ❌ 

I cannot explain where it comes from, but I think loading Fontawesome after my viewer overwrites the Fontawesome CSS rules (which is no problem).

Good
![image](https://user-images.githubusercontent.com/520039/119327957-d712c000-bc83-11eb-8840-e02c9122e22c.png)

Bad
![image](https://user-images.githubusercontent.com/520039/119327993-e3971880-bc83-11eb-8cdd-d1e0e702503a.png)

So I think by switching the order of scripts

Current situation on your website (only head)
```
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="src/light_favicon.svg"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="jsFavourite.js"></script>
    <script src="jsMatches.js"></script>
    <script src="node_modules/@mliebelt/pgn-viewer/lib/pgnv.js" type="text/javascript" ></script>
```

Better
```
    <link rel="icon" type="image/png" href="src/light_favicon.svg"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="jsFavourite.js"></script>
    <script src="jsMatches.js"></script>
    <script src="node_modules/@mliebelt/pgn-viewer/lib/pgnv.js" type="text/javascript" ></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
```

**Comment by imprudenza** [comment]
Thank you so much for the huge help! Everything works now :)

Super work and super library
