### ISSUE TITLE
Another strange display of variations

### ISSUE THREAD

**Issue by braoult** [mliebelt/PgnViewerJS#244]
In list notation (inline looks correct), the game below does not display correctly: The second 14th black variation `(14... axb5 15. Qxb5 Bd7 16. Qb3)` is displayed in a second column right of first variation. In fact, even the 15. Rb1 comment has also a strange display (placed after a variation, and having 3 dots just before.

```
1. d4 Nf6 2. c4 g6 3. Nc3 Bg7 4. g3 O-O 5. Bg2 c6 6. e3 d6 7. Nge2 e5 8. O-O Nbd7 9. b4 Rb8 10. d5 c5 11. a3 a6 12. b5 Nb6
13. Qb3 Bf5 14. e4 Bg4
  (14...   Bd7
   15. Rb1 {dans idee b6 sur Cb6 bouge}
     (15. Bg5 axb5 16. Nxb5)
   15... axb5
     (15... a5 16. Bd2 {pression sur a5})
   16. Nxb5)
  (14... axb5 15. Qxb5 Bd7 16. Qb3)
15. f3 Bd7 1-0
```

I did double check in Configuration Builder, and the display also looks like:
```
14.    Bd7                Bg4
( 14... Bd7                                  ( 14...
 ( 15. Bg5 axb5 16. Nxb5) 15.Rb1             axb5 15.
 ( 15... a6 16. Bd2 ... pression sur a5      Qxb5 Bd7 16.
)                                            Qb3 )
... dans idee b6 sur Cb6 bouge
axb5 16.Nxb5 )
15.    f3                 Bd7
```

**Comment by mliebelt** [comment]
Thanks for bringing that to my attention. I was already aware, that there may be some cases where list layout does not work as expected. No so easy to diagnose, so I will try to bring that to a more minimal setup, and then to see how many problems I have. Surely one of the things I want to fix soon.

As long as this layout is not reliable, please use inline instead.

**Comment by braoult** [comment]
Not sure if I should open a new ticket, because it was visible in my example, but when you have a comment for white move, let say 1. e4 { this is a comment } 1... e5

**Comment by mliebelt** [comment]
To your original ticket, I found the following improvement (not finished), CSS is now much better

![image](https://user-images.githubusercontent.com/520039/120923540-65009900-c6cf-11eb-954e-eec3ec9030cd.png)

Will continue later on it. About that with the comment, you may file another ticket.

**Comment by mliebelt** [comment]
See the new examples in the directory `examples/tickets` as well as the many variations in `examples/configuation/moves/list-layout.html`.
