### ISSUE TITLE
display issues with comments and sub-variations 

### ISSUE THREAD

**Issue by braoult** [mliebelt/PgnViewerJS#245]
Making more testing following bug #244,  I noticed two display issues that I nailed down with this small example :
`1. e4 { comment } 1... e5 ( 1... d5 2. d4 ( 2. c4 c5 ) ) 2. d4`

The display (inline mode) is :

**1. e4** comment **e5**
**_( 1... d5_**
 ( 2. c4 c5 )
**_2. d4 )_**
**2. d4**

Issue #1 is that the first black move, which follows  a comment, should have the move number (`1... e5` instead of `e5`).
Issue #2 is that the 2nd level sub-variation `2. c4 c5` should be displayed after the 1rst level variation 2nd white move.

The display should be:

**1. e4** comment **1... e5**
**_( 1... d5 2. d4_**
 ( 2. c4 c5 ) **)**
**2. d4**

**Comment by mliebelt** [comment]
Thanks for bringing that up. Hopefully, the fix will be easy. I have already seen in #244 that your issue nr. 2 is the order of the first level variation. The nr. 1 should be easy as well.

**Comment by mliebelt** [comment]
I have worked on all tickets and hopefully got all right. I have not the time to do a new release, but I will deploy the current state on the Configuration Builder, so you are able to play with it. I will do a new release as soon as I have the necessary time for doing it.

**Comment by mliebelt** [comment]
Reopened due to this

![image](https://user-images.githubusercontent.com/520039/120933916-8a57cc00-c6fc-11eb-801a-41160179b257.png)

Here the move number is missing.
