### ISSUE TITLE
[Display] : Castle moves wrap on 2 lines

### ISSUE THREAD

**Issue by braoult** [mliebelt/PgnViewerJS#246]
With the following game `1. e4 e5 { comment to push O-O-O to right } 2. Nc3 Nc6 3. d3 d6 4. Be3 Be6 5. Qd2 Qd7 6. O-O-O O-O-O`, castle move (O-O-O in this case is wrapped on 2 lines).

To reproduce, you may have to change the comment length in game above, depending on your font size.

I noticed that on my web site a few days ago, and I tried the following CSS rule :
```
.pgnvjs .move > a {
  white-space: nowrap;
}
```
Castle move do not split anymore, however there are some side effects: it looks like the whole move (white + black) do not wrap anymore (i.e. white move cannot be separated from black move).

**Comment by braoult** [comment]
Not sure I would be satisfactory/acceptable, but I found a possible workaround on 
[stackoverflow](https://stackoverflow.com/questions/7691569/no-line-break-after-a-hyphen), which would be to replace hyphens in castle moves with non-breaking hyphen : `&#8209;`.

**Comment by mliebelt** [comment]
There is a simple fix by adding the CSS rule: 

```
.pgnvjs .moves > .move {
    display: inline-block;
}
```

**Comment by mliebelt** [comment]
See this with the configuration builder.

![image](https://user-images.githubusercontent.com/520039/120933746-cb031580-c6fb-11eb-9c89-0210eb6b85b9.png)

**Comment by braoult** [comment]
Thank you !

I just did the tests on my site also, adding this CSS locally, and moving the castle moves to the right little by little, and the moves went to the right place when they should, just perfect.

**Comment by braoult** [comment]
Just a question, as I know nothing about NPM : I get the distribution by cloning from github. Instead of building with NPM, may I always use the "docs/lib/pgnv.js" for my own use ? I mean, is it a kind of "pre-release" build than can be used for testing ?

**Comment by mliebelt** [comment]
@braoult You may use that pre-release, but there is no information available what is included in that version and what not. I try to publish the current state there, so it is easier to test some functionality, but sometimes I forget this. So the save way is to use a clone of the repository, and to use the recipe in [dev.md](https://github.com/mliebelt/PgnViewerJS/blob/master/dev.md).
