### ISSUE TITLE
Allow to define strings for NAGs

### ISSUE THREAD

**Issue by braoult** [mliebelt/PgnViewerJS#247]
Some NAGs are unknown by PgnViewerJS, and currently displayed "as-is" (for example "$11").

It would be nice to have a way to configure them in javascript, without having to rebuild pgnviewer.

**Comment by mliebelt** [comment]
Correction: The [official specification](https://github.com/mliebelt/pgn-spec-commented/blob/main/pgn-specification.md#10-numeric-annotation-glyphs) does not include information about the symbols to use. The [wikipedia page ](https://en.wikipedia.org/wiki/Numeric_Annotation_Glyphs) about NAGs includes the symbols used, if there are any. As you can see there, $11/$12 have no symbol set. So it is not that "PGNViewerJS does not know the NAGs".

What is the value to have a symbol that noone (besides the creator) knows? I don't understand how that will work at the end ...

**Comment by braoult** [comment]
I know there is no symbol for "$11"on the Wikipedia page.

However, "$11" means something (equal chances, quiet position).

In that sense, if you have this "$11" in a given PGN, you would prefer for instance use "=" instead of "$11".
For "$9" (Worst Move), one would maybe prefer to have "??" instead of "$9".

Some could even prefer to replace "$11" with a string, like "=, [quiet]" (I am not a fan of this however).

By looking at the different NAGs I have in my PGNs, I get:
```
$ grep -hoE "\\\$[0-9]+" *.pgn | sort -nu -k 1.2 | paste -sd " "
$1 $2 $3 $4 $5 $6 $10 $11 $13 $14 $15 $16 $17 $18 $19 $132 $138
```

How did I get those NAGS that "no one knows" ? Probably with ChessBase which I was using end 90's. I did not know what was a NAG at that time, but I was probably able to input these symbols one way or another. I don't remember how ChessBase did display them however.

Therefore, it is likely these symbols are in use (even if not often), and that you people use them too, and that we could find such NAGs in publicly shared PGNs as in those (huge) ones I found on the web long ago:

```
$ ls -lh
total 2.1G
-rw-r--r-- 1 br br  14M Feb 18  2009 current 2008.pgn
-r--r--r-- 1 br br 903M Oct  6  2005 enormous.pgn
-rw-rw-r-- 1 br br 1.2G Aug 17  2008 Million_updated.pgn
$ grep -hoE "\\\$[0-9]+" *.pgn | sort -nu -k 1.2 | paste -sd " "
$1 $2 $3 $4 $5 $6 $7 $8 $9 $10 $11 $13 $14 $15 $16 $17 $18 $19 $30 $38 $40 $42 $44 $46 $90 $132 $136 $138 $146
```

As an example of what could be done, I just made a test with the game `1. e4 $9 e5 $11 { comment to push O-O-O to right and right } 2. Nc3 Nc6 3. d3 d6 4. Be3 Be6 5. Qd2 Qd7 6. O-O-O O-O-O *`

PgnViewerJS will display :
![image](https://user-images.githubusercontent.com/8958429/120965350-13a2e900-c765-11eb-9a07-905cca6910ba.png)

While Scid vs PC will display :
![image](https://user-images.githubusercontent.com/8958429/120965166-c58de580-c764-11eb-9e65-bef3008b28f0.png)

And ChessX :
![image](https://user-images.githubusercontent.com/8958429/120965499-42b95a80-c765-11eb-9cb1-dcca5566c627.png)

What do you think about it ?

**Comment by braoult** [comment]
If this can help, this is a link to [ChessX's NAG handling](https://github.com/Isarhamster/chessx/blob/master/src/database/nag.cpp).

Apparently (I did not look deeply), they are able to display NAGs 2 ways: "short" (like "!") or "long" ("Good Move"). However, I did not find this option anywhere, maybe it will be handled later, I am not sure.

**Comment by mliebelt** [comment]
I found a solution that allows anyone to add special symbols if they want. It works like that:

* Hold the value of the in attribute `data=value` (e.g. `<nag data-value="$11" title="..."></nag>
* Display the value as content by using CSS only: `.pgnvjs .moves move nag::before { content: attr(data-value); }`
* By adding special rules individually, you may overwrite that content: `.pgnvjs .moves move nag[data-value="$11"]::before { content: "="; }`

This does not change anything else, and the users are free to use whichever symbols they want to use.

**Comment by braoult** [comment]
Thanks a lot, I like this simple-to-use solution !

I will add something about the Wikipedia NAGs page on the NAG discussion (in one word: I don't consider it authoritative at all).
This is related to the sentence "The wikipedia page about NAGs includes the symbols used, if there are any." I don't agree: I did add one today, you may add some too, and even some can be wrong.
