### ISSUE TITLE
French translation is incomplete

### ISSUE THREAD

**Issue by braoult** [mliebelt/PgnViewerJS#254]
I will do it, please give me a few days.

I have a question first:
```
    "nag:$10": "drawish position or even",
    "nag:$10_menu": "Equal position",
```
What are the contexts of the use of these two strings ?

**Comment by mliebelt** [comment]
![image](https://user-images.githubusercontent.com/520039/121691975-df625c00-cac7-11eb-9134-9872baa1d8e2.png)

This shows `pgnEdit` which has a menu for NAGs. The menu elements of that menu get the translation of `$10_menu`. The other one is the official text from the [Pgn Specification](https://en.wikipedia.org/wiki/Numeric_Annotation_Glyphs) with the better description from Wikipedia. This text is not really used at the moment, but could be, e.g. by having a popup for the NAGs.

**Comment by braoult** [comment]
Oh, I will have to fix the [PGN french wikipedia page](https://fr.wikipedia.org/wiki/Portable_Game_Notation#NAG) too, NAGs explanation is just incorrect :-)

**Comment by braoult** [comment]
During translation, I found (in en.js) the following:
```
    "nag:$36": "White has the initiative",
    "nag:$36_menu": "Attack",
    "nag:$37": "Black has the initiative",
    [...]
    "nag:$40": "White has the attack",
    "nag:$40_menu": "Initiative",
    "nag:$41": "Black has the attack",
```
I wonder if `36_menu` and `40_menu` are reversed ?

**Comment by mliebelt** [comment]
True, this is a bug. I will just fix it in the language files, and check the other ones (except french) as well.

**Comment by braoult** [comment]
I finished a 1st version of french translation.
I will ne be able to make a pull request for this file alone, my git repo is totally messy after a "reset hard", I will need to restart from scratch and make proper branching.
Meantime, would it be acceptable if I send you the file itself, or do you prefer to wait ?

**Comment by mliebelt** [comment]
Well, I don't care. You may do a branch from some state of the master, and then do create a pull request from that. Because it is only one file, that should not be a problem. Having a branch (and pull request then) allows me to integrate it more easily later. If you attach the file, e.g. to this issue, your credentials are lost, because then I will do the commit.

Decide on your own, I think you are the one that needs that change the most.

**Comment by braoult** [comment]
PR #256
