### ISSUE TITLE
Move number missing after end of variant 2 in variant 1

### ISSUE THREAD

**Issue by braoult** [mliebelt/PgnViewerJS#261]
Maybe related to [this previous issue](https://github.com/mliebelt/PgnViewerJS/issues/245#issuecomment-855432642).

With the PGN `1. e4 (1. d4 d5 2. c4 (2. Nf3 Nf6) 2... c5) 1... e5`, the display is :

![image](https://user-images.githubusercontent.com/8958429/121810055-90e7c580-cc5f-11eb-917d-f0ac1b93c9b4.png)

The move number is missing for the variation move `2... c5`.

To help debug, it should noted that when we add a comment just before `2.... c5`, eg: `1. e4 (1. d4 d5 2. c4 (2. Nf3 Nf6) {comment} 2... c5) 1... e5`, the display is correct (fixed in [this commit](https://github.com/mliebelt/PgnViewerJS/commit/0a57b25a514f59a6fa2ce46bb4fd31a45a3f2693)):
![image](https://user-images.githubusercontent.com/8958429/121810175-0d7aa400-cc60-11eb-9c43-5f2a89a028cb.png)

**Comment by mliebelt** [comment]
So seems to be a variant to the previous one found. The  rules are really complicated, I will check them again. One question: would it possible to just have a title? I will flag it as bug (or you could do it), but I like clean speaking titles much more.

A better one could e.g. be: "Move number missing after end of variant 2 in variant 1".
