### ISSUE TITLE
NAG editing broken in pgnEdit

### ISSUE THREAD

**Issue by vonschultz** [mliebelt/PgnViewerJS#263]
**Way to reproduce**

1. Create a pgnEdit board. You can use https://mliebelt.github.io/PgnViewerJS/examples.html#1003 for this.
2. Make a move, for example "1. e4", by clicking in the board.
3. Open the "NAGs menu", by clicking the corresponding icon.
4. Try clicking "Good move" (or any other NAG).

**Expected result**

I expect to see "1. e4!" in the boardMoves div, and no errors in the console.

**Actual result**

The boardMoves div is stuck at "1. e4", and `Uncaught TypeError: document.querySelector(...) is null` appears in the console (Firefox version 78.11.0esr) or `Uncaught TypeError: Cannot set property 'textContent' of null` appears in the console (Chromium version 91.0.4472.77)

**Comment by mliebelt** [comment]
Yeah, true, i know that, but was concentrating lately on refacorings for pgnView (and was breaking then the edit mode). I try to have a look, if there is an easy fix available. There are some more things broken currently in edit mode (handling of variations), but I had no time to address them.
Thank you for raising that issue.

**Comment by mliebelt** [comment]
So I refactored a little bit, and it was easy to fix. Hopefully without other degradation. I have deployed that state (without building a new release) to https://mliebelt.github.io/PgnViewerJS/examples.html#1003, so you should be able to test it there.
