### ISSUE TITLE
Parsing PGN from DGT board output

### ISSUE THREAD

**Issue by matt-d-webb** [mliebelt/PgnViewerJS#269]
I am having to carry out some data cleansing on the pgn's that are produced from the DGT boards we use during our events to the retrospectively display on our site.

I figured it would perhaps be best to have this resolved at source (maybe). Below is an example of an untouched PGN from a DGT board:

```
[ePGN "0.1;DGT LiveChess/2.2"]
[Event "May Open Congress"]
[Site "The Chess Centre, Ilkley, United Kingdom"]
[Date "2021.05.22"]
[Round "2.1"]
[White "Wainwright, Andrew"]
[Black "Shaw, Peter"]
[Result "0-1"]
[TimeControl "60 mins"]
[BlackElo "2172"]

1. e4 {[%clk 00:59:44]} {[%emt 00:00:16]} d6 {[%emt 00:00:35]} 2. d4 {[%clk
00:59:26]} Nf6 {[%clk 00:59:38]} {[%emt 00:00:05]} 3. Bd3 {[%clk 00:59:06]}
{[%emt 00:00:20]} Nc6 {[%clk 00:58:28]} {[%emt 00:01:10]} 4. c3 {[%clk
00:58:35]} {[%emt 00:00:30]} e5 {[%clk 00:58:14]} {[%emt 00:00:15]} 5. d5
{[%clk 00:57:52]} {[%emt 00:00:42]} Ne7 {[%clk 00:58:04]} {[%emt 00:00:10]} 6.
Bg5 {[%clk 00:57:42]} {[%emt 00:00:10]} Ng6 {[%clk 00:57:22]} {[%emt 00:00:42]}
7. h3 {[%clk 00:57:22]} {[%emt 00:00:19]} Be7 {[%clk 00:56:34]} {[%emt
00:00:49]} 8. Nd2 {[%clk 00:56:51]} {[%emt 00:00:30]} Nxd5 {[%clk 00:54:41]}
{[%emt 00:01:55]} 9. Bxe7 {[%clk 00:54:42]} {[%emt 00:02:08]} Ndxe7 {[%clk
00:54:34]} {[%emt 00:00:06]} 10. Ngf3 {[%clk 00:54:30]} {[%emt 00:00:13]} Nf4
{[%clk 00:52:54]} {[%emt 00:01:40]} 11. Bf1 {[%clk 00:54:16]} {[%emt 00:00:14]}
O-O {[%clk 00:52:29]} {[%emt 00:00:25]} 12. g3 {[%clk 00:54:10]} {[%emt
00:00:06]} Ne6 {[%clk 00:52:09]} {[%emt 00:00:20]} 13. Bc4 {[%clk 00:53:10]}
{[%emt 00:01:00]} c6 {[%clk 00:51:24]} {[%emt 00:00:46]} 14. Qe2 {[%clk
00:52:32]} {[%emt 00:00:37]} d5 {[%clk 00:49:15]} {[%emt 00:02:09]} 15. exd5
{[%clk 00:52:14]} {[%emt 00:00:18]} cxd5 {[%clk 00:49:10]} {[%emt 00:00:05]} 16.
Bb3 {[%clk 00:52:04]} {[%emt 00:00:10]} f6 {[%clk 00:48:54]} {[%emt 00:00:16]}
17. O-O-O {[%clk 00:51:51]} {[%emt 00:00:13]} Nc5 {[%clk 00:47:51]} {[%emt
00:01:02]} 18. h4 {[%clk 00:51:19]} {[%emt 00:00:32]} Bf5 {[%clk 00:44:58]}
{[%emt 00:02:53]} 19. Nc4 {[%clk 00:48:56]} {[%emt 00:02:22]} Nxb3+ {[%clk
00:42:07]} {[%emt 00:02:51]} 20. axb3 {[%clk 00:48:48]} {[%emt 00:00:08]} Qc7
{[%clk 00:40:20]} {[%emt 00:01:47]} 21. Ne3 {[%clk 00:47:38]} {[%emt 00:01:10]}
Be4 {[%clk 00:40:13]} {[%emt 00:00:06]} 22. Rhe1 {[%clk 00:47:31]} {[%emt
00:00:06]} Rfc8 {[%clk 00:34:03]} {[%emt 00:06:11]} 23. Nd2 {[%clk 00:46:25]}
{[%emt 00:01:07]} Bg6 {[%clk 00:33:57]} {[%emt 00:00:06]} 24. Qb5 {[%clk
00:45:38]} {[%emt 00:00:47]} a6 {[%clk 00:33:13]} {[%emt 00:00:45]} 25. Qb4
{[%clk 00:43:23]} {[%emt 00:02:15]} b5 {[%clk 00:28:49]} {[%emt 00:04:24]} 26.
Nc2 {[%clk 00:41:03]} {[%emt 00:02:19]} d4 {[%clk 00:27:09]} {[%emt 00:01:39]}
27. c4 {[%clk 00:40:55]} {[%emt 00:00:10]} bxc4 {[%clk 00:25:09]} {[%emt
00:02:00]} 28. Qxc4+ {[%clk 00:40:54]} Kh8 {[%clk 00:24:24]} {[%emt 00:00:44]}
29. Qxc7 {[%clk 00:40:25]} {[%emt 00:00:29]} Rxc7 {[%clk 00:24:19]} {[%emt
00:00:05]} 30. Nc4 {[%clk 00:40:23]} {[%emt 00:00:01]} Rb8 {[%clk 00:23:00]}
{[%emt 00:01:19]} 31. N2a3 {[%clk 00:39:59]} {[%emt 00:00:25]} Rxb3 {[%clk
00:22:41]} {[%emt 00:00:19]} 32. Kd2 {[%clk 00:39:22]} {[%emt 00:00:37]} Nd5
{[%clk 00:19:59]} {[%emt 00:02:42]} 33. Rc1 {[%clk 00:39:11]} {[%emt 00:00:12]}
h6 {[%clk 00:19:25]} {[%emt 00:00:34]} 34. g4 {[%clk 00:36:22]} {[%emt
00:02:49]} Nf4 {[%clk 00:18:24]} {[%emt 00:01:01]} 35. g5 {[%clk 00:36:04]}
{[%emt 00:00:18]} Rd3+ {[%clk 00:17:50]} {[%emt 00:00:34]} 0-1
```

This specific example, I am not entirely ensure sure why it produces the following error:

Expected "+", "/", or "\"" but " " found.

I've started to strip out the data to narrow down the root cause, but still the error remains:

![image](https://user-images.githubusercontent.com/36933715/133007176-7cda319a-96b0-4130-aa97-3291e83b1aa3.png)

Attempts to remove line breaks, take out suspicious looking strings (i.e "0.1;DGT LiveChess/2.2") hasn't resolved the issue, yet.

**Comment by mliebelt** [comment]
I am currently away from home, and therefore not able to fix your problem, I will do that after my return. It is related to parsing the tags, where offset 194 is the numbers of character from the beginning. I will have to change the pgn-parser to fix your problem.

Nice to have the first time the export of a DGT board, I don't think their specification is public.

**Comment by mliebelt** [comment]
I found the problem. "60 minutes" is not a valid time control [according to the spec](https://github.com/mliebelt/pgn-spec-commented/blob/main/pgn-specification.md#961-tag-timecontrol). You should use instead just "3600", that means the number of seconds.

Of course it will be possible to have an additional rule for minutes, but the DGT people should fix their implementation.

**Comment by matt-d-webb** [comment]
@mliebelt Hey! Thank you for getting back to me so quickly.

Ah, thanks for highlighting that, I can remove that easily enough in my upload service. The DGT LiveViewer GUI has a freeform text field for time, hence the "60 mins".

I can pass this on to them as I've raised another bug with them previously.

**Comment by mliebelt** [comment]
This issue was fixed through the updated version of pgn-parser (1.4.0).
