### ISSUE TITLE
pawn promotion? 

### ISSUE THREAD

**Issue by Mehmet82** [mliebelt/PgnViewerJS#29]
Thank you very much for PGN viewer. How will the choices made while pawn promotion? queen, rook, knight or bishop. Thanks you.

**Comment by mliebelt** [comment]
Currently, pawns are promoted in edit mode automatically to a queen (I have checked that with http://mliebelt.github.io/PgnViewerJS/docu/examples2.html#1003, played there enough moves to promote a pawn). So currently, it is not possible to underpromote a pawn.

For the viewer mode, you just include the figure symbol in the notation. You may see one example by doing the following:

1. Open http://mliebelt.github.io/PgnViewerJS/docu/example/config.html
2. Select Modus == pgnView
3. Insert into the PGN text field the following moves: 1. e4 f5 2. exf5 g6 3. fxg6 Bg7 4. gxh7 Kf7 5. hxg8=N
4. You should be now been able to play the moves with the underpromotion.

See https://en.wikipedia.org/wiki/Portable_Game_Notation and search for promotion there to see the definition of it. The figure symbols have to be English only (R,N,B,Q).

**Comment by Mehmet82** [comment]
Thank you for the answer.

**Comment by mliebelt** [comment]
See #30 for the bug "Underpromotion in Edit mode"
