### ISSUE TITLE
Use Typescript instead of Javascript for pgn-reader

### ISSUE THREAD

**Issue by mliebelt** [mliebelt/PgnViewerJS#310]
After having moved pgn-parser to Typescript, I have now information about the structure read by the parser. It would be quite handy to use that structure, but that is only possible if the reader would use Typescript.

This should work from the beginning, and by using types, I expect to find some bugs sprinkled over the code  base.

Here are the jobs to do (should be done on a branch, to be sure):

- [x] Ensure that code is syntactically correct.
- [x] Type the main methods that are used in the API of the reader.
- [x] Ensure that all tests run again.
- [x] Add additional tests for the new extracted functionality. ✔️  Done up to `When reading game with an end`
- [x] Add additional tests for all possible calls to the API, with some edge cases included.

**Comment by coffeeDev98** [comment]
Hey @mliebelt,
Would love to be of help in this project, if possible.

**Comment by mliebelt** [comment]
I started the weekend with the migration, so I will share what I currently have as branch. The code is not compiling at the moment, so it will take some time until someone can work on that as well. Thank's a lot for your help!

**Comment by coffeeDev98** [comment]
@mliebelt, Just curious, Is there any reason why you didn't get into gameplay for PGNViewer. Like, chessground's functionalities... to control what to do when a player moves a piece, etc...
Would like an opportunity to discuss this with you...

**Comment by mliebelt** [comment]
Can we move that to a discussion? I think it does not fit under the label Typescript, so I would like to split that then. Feel free to start a discussion to that topic then.

**Comment by coffeeDev98** [comment]
Yes, I've created a new discussion([here](https://github.com/mliebelt/PgnViewerJS/discussions/319))

**Comment by mliebelt** [comment]
I close the ticket now, because everything obvious is done, and remaining tasks will be done on the fly, or lead to new tickets.
