### ISSUE TITLE
Using pgnFile in test cases (node.js) and the browser

### ISSUE THREAD

**Issue by mliebelt** [mliebelt/PgnViewerJS#323]
I noticed that using option `pgnFile` works only, if there is a local web server or so running, so that the file name is the path of that file on the web server. It is not (easily) possible to have a local file loaded without tricks.

**Comment by mliebelt** [comment]
I found the following configuration which somehow worked:

    pgnFile: 'file://' + path.resolve(__dirname, './2games.pgn'), manyGames: true

That is a neat trick, but not so easy to find. It should be possible to do the following for the reader:

* Try to take the URL as given (in that case the name itself: `./2games.pgn`).
* Try then to add the local directory and `file:` prefix to it.
* If that does not work, throw an error.

**Comment by mliebelt** [comment]
Later on, I have seen that depending on how the module is built, this does not work at all. It seems to be tricky to have a solution that works both with node.js and in the browser, and is able to read a local file (at least needed for node.js in the test cases), and to use fetch or XmlHttpRequest only in the browser.

Therefore, the test cases are disabled at the moment. This has of course be solved before a new version of both pgn-reader and pgn-viewer is published.

**Comment by ulthiel** [comment]
I tested this in Firefox and the Web Developer Tools showed me the [Reason: CORS request not HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CORS/Errors/CORSRequestNotHttp) error. I think, reading a local file just doesn't work anymore in modern browsers. It needs to be a remote source.

**Comment by mliebelt** [comment]
> I tested this in Firefox and the Web Developer Tools showed me the [Reason: CORS request not HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CORS/Errors/CORSRequestNotHttp) error. I think, reading a local file just doesn't work anymore in modern browsers. It needs to be a remote source.

Just that I understand your remark: Had you a local web server running or not? I think the old `file:// ...` kind of calling it is not working any more. And to be fair, I don't care, because having an (embedded) small web server started, before using the tool locally is not a problem.

**Comment by ulthiel** [comment]
No web server, just tried reading a local file.
