### ISSUE TITLE
Game comment in edit and view mode

### ISSUE THREAD

**Issue by mliebelt** [mliebelt/PgnViewerJS#338]
It should be possible to enter a so called game comment (the one before the first move). This is currently ignored in the UI. The game comment in view mode is parsed in contained in the parse tree, but not shown when the game is rendered.

**Comment by jackstenglein** [comment]
Hello, I would like to request that this issue get moved up in the priority queue. We are using this library on https://www.chessdojo.club, and some users have been asking for this feature.
