### ISSUE TITLE
Add a link to the examples directory to the readme.md in the 'dist' directory

### ISSUE THREAD

**Issue by jukey** [mliebelt/PgnViewerJS#34]
After downloading the latest version as [zip file](https://github.com/mliebelt/PgnViewerJS/blob/master/dist/PgnViewerJS-0.9.2.zip) from the 'dist' folder I checked the readme.md that references an 'example' folder that is not part of the zip file.

The easiest solution would be to include a [link to the examples directory](https://github.com/mliebelt/PgnViewerJS/tree/master/dist/examples) within the ['dist' directory](https://github.com/mliebelt/PgnViewerJS/tree/master/dist) into the readme.md.

**Comment by mliebelt** [comment]
Good idea, I will check that and include it in the next version.

**Comment by mliebelt** [comment]
Just checked it again: the examples were included in the distro 0.9.1, and where excluded (for whatever reason) from distro 0.9.2. I will fix that, and perhaps provide an `index.html` file (instead or additional to `readme.md`) and link the examples there.

**Comment by mliebelt** [comment]
Added file `readme.html` in the same directory, will be included in the distribution. `readme.md` links now to the included example files as well.
