### ISSUE TITLE
incorrect PGN representation when black moves first

### ISSUE THREAD

**Issue by coffeeDev98** [mliebelt/PgnViewerJS#395]
Hey @mliebelt ,

You had previously resolved an issue where pgn-viewer crashes if black had to start first(#354 ) . I think, in that fix.. this case of PGN handling was missed.

If you see the PGN representation, when black has to move first, after playing a move... the PGN starts with `1... g5 2. h4 gxh4 3. g4 hxg3 *` whereas in pgn-viewer it is `g5 2. h4 gxh4 3. g4 hxg3 *`

This breaks the UI in `list` view mode for pgn-viewer.

PGNViewer Screen
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/63295908/193870891-3ea5133f-ac1a-447a-8840-9a6a22e89d46.png">

Lichess Screen (for illustration purpose)
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/63295908/193872327-208df771-c87b-4206-b1fd-5157b31a6ba3.png">

**Comment by coffeeDev98** [comment]
Hey @mliebelt , 
I've implemented somewhat of a fix which seems to work. It seems a bit hacky though. I can create a PR for this if it's okay...

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/63295908/198928222-5495a458-d902-4266-b636-e328a3ea7d89.png">

**Comment by mliebelt** [comment]
Do that, I was not able to investigate any time into the issue. I will look on it, and perhaps find a better / easier way to do it.

**Comment by coffeeDev98** [comment]
Created a PR for this #400

**Comment by mliebelt** [comment]
Found a simpler, easier to understand solution. Had to fix pgn-viewer first ... ( see #409 )
