### ISSUE TITLE
Use FontAwesome for the UI (and the buttons)

### ISSUE THREAD

**Issue by mliebelt** [mliebelt/PgnViewerJS#4]
I saw a reference lately to http://fontawesome.io/ and liked it a lot. Try to build a style where the video player icons are used (http://fontawesome.io/icons/#video-player).

I am sure that there are additional icons there that could be used as well for editing and other things.

**Comment by steinitz** [comment]
I had some luck using google's material design font icons (with materialize.css).  I did it by changing part of pgnvjs.css from this:

div.buttons > .prev {
	background-image: url("../img/buttons/ff/resultset_previous.png");
}
div.buttons > .next {
    background-image: url("../img/buttons/ff/resultset_next.png");
}
div.buttons > .first {
	background-image: url("../img/buttons/ff/resultset_first.png");
}
div.buttons > .last {
	background-image: url("../img/buttons/ff/resultset_last.png");
}
div.buttons > .play {
	background-image: url("../img/buttons/ff/control_play_blue.png");
}
div.buttons > .play {
    position:relative;
}
div.buttons > .stop {
	background-image: url("../img/buttons/ff/control_pause_blue.png");
}
div.buttons > .flipper {
	background-image: url("../img/blackwhite-flipper.vers1.png");
}

to this:

div.buttons > .prev:after {
	content: "\e6aa";
}
div.buttons > .next:after {
	content: "\e6a9";
}
div.buttons > .first:after {
	content: "\e6c9";
}
div.buttons > .last:after {
	content: "\e6c8";
}
div.buttons > .flipper:after {
	content: "\e680";
}
div.buttons > .play:after {
	content: "\e6bb";
}
div.buttons > .stop:after {
	content: "\e6ba";
}

Which all assumes that the google's font is accessible and that the materialize.css classes are available.  Note that it's probably possible to use symbols for the font numbers.

Cheers,

Steve

**Comment by mliebelt** [comment]
Created new versions for a lot of examples, and replaced the previous style with font awesome. There are now three styles available which have an effect on the buttons:

* default: uses font awesome style
* green: uses the tango theme (see http://tango.freedesktop.org/Tango_Icon_Library for the source)
* blue: See http://www.famfamfam.com/lab/icons/silk/ for the source of this
