### ISSUE TITLE
Integration with scoutfish

### ISSUE THREAD

**Issue by mcostalba** [mliebelt/PgnViewerJS#41]
Are you interested in integrating your viewer with https://github.com/mcostalba/scoutfish?

Scoutfish is a powerful searching tool with inside chess knowledge that is able to quickly find a subset of games matching a set of flexible and powerful conditions very quickly even in very big PGN databases. The output is a list of the games PGN.

What is missed  is a way to allow the user to graphically define a query. In case you are interested please get a look at the README.md in the above link and let me know. Thanks.

**Comment by cgencer** [comment]
I will, and also am thinking of a few features as well (which need serverside), so I will dig more into your code and maybe create a fork/branch with some node.js backend as well. ;)

**Comment by mliebelt** [comment]
Well, that ticket was now open for 3.5 years, and there is no chance at all that I may integrate ever scoutfish. So I will close that ticket.
