### ISSUE TITLE
Opposition pawn isn't removed after En passant execution. 

### ISSUE THREAD

**Issue by coffeeDev98** [mliebelt/PgnViewerJS#411]
Hey @mliebelt ,

There's an issue in executing En passant with the latest version of PGNV. The opposition pawn is left on the board after an en passant move for all following moves.
Although this doesn't occur when iterating through the moves in View/Edit mode. It happens when playing/moving the pieces on the board.

Expected: Piece is removed after en passant.

Actual: 

https://user-images.githubusercontent.com/63295908/211770865-27163553-a794-44f6-9f70-17689954161c.mov

Also,
When trying to print the PGN for when black starts first, the starting `1...` does not come. Ref: #395 #409 #108

**Comment by mliebelt** [comment]
Thank you for reporting that. I tried to reproduce that behavior with the configuration builder, selection mode == pgnEdit, but was not able to reproduce it. Then I looked at your video, and there I have the same behavior. The moves 

```1. d4  f5 2. Nc3 f4 3. e4 fxe3```

work as expected. I have to analyse where the difference comes from, but it is strange ...

**Comment by mliebelt** [comment]
Ok, found the reason:

* Moves done by parsing notation, and playing, use the FEN generated for each move.
* When playing a move on the board, the move is checked by `chess.js`, and the flag EP_CAPTURE is noticed, but notation.ep is not set.
* But `notation.ep` is checked then by the player, so the pawn is not removed.

**Comment by coffeeDev98** [comment]
Could it be because of the commented line #769 in pgn.ts?
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/63295908/212258850-5169178b-da26-4953-8b1a-ae6a993cab14.png">

**Comment by mliebelt** [comment]
Integrated the changes in the  gh pages version http://mliebelt.github.io/PgnViewerJS/config/config.html to demonstrate that it has been fixed. Did a new version for pgn-reader (to import that in pgn-viewer), but no new release for pgn-viewer.
