### ISSUE TITLE
In 'list' mode, first white move is '...'

### ISSUE THREAD

**Issue by braoult** [mliebelt/PgnViewerJS#412]
I just installed latest version (with `npm install @mliebelt/pgn-viewer`). `dist.js` is dated `Jan 17 17:16` (UTC), its size is 949069 bytes.

When using `pgn-viewer` in `inline` mode, there is no issue. However, `list` mode "skips" the first white move ("..."), and displays it in black column (on the right). After that, all black moves are on the left, and white moves (including move number) are on the right :

![pgn-viewer](https://user-images.githubusercontent.com/8958429/214658160-45651137-6366-4028-a7aa-cee34693a8a5.png)

The PGN used for the example above is :
```
[Event "Casual Rapid"]
[Site "Conflans Ste Honorine FRA"]
[Date "1991.??.??"]
[Round "?"]
[White "Valentin, Alain"]
[Black "Raoult, Bruno"]
[Result "0-1"]
[WhiteElo "1660"]
[BlackElo "1730"]
[ECO "D35"]
[Opening "QGD: Exchange, 5.Nf3 Be7 6.Bf4"]
[PlyCount "32"]

1. d4 Nf6 2. c4 e6 3. Nf3 d5 4. cxd5 exd5 5. Nc3 Be7 6. Bf4 O-O 7. Qc2 Nc6
8. e3 Bb4 9. Bd3 Re8 10. O-O Bxc3 11. Qxc3 Ne4 12. Qc2 Bf5 13. Ne5 Nb4 14.
Qd1 Nxd3 15. Qxd3 Ng3 16. Qc3 Ne2+ 0-1
```

**Note :** I thought it could be a parsing issue with the space between first move number and white move, and tried with `1.d4 Nf6` instead of `1. d4 Nf6`, but output is the same...

**Comment by mliebelt** [comment]
Ok, I did a fix for this already (try it on https://mliebelt.github.io/PgnViewerJS/config/config.html), but I have not released a new version. Will do that now, and think that this will fix the problem.

**Comment by braoult** [comment]
I noticed it was fine with the `Config Builder`, but I did not write it on my report (I was unsure if this builder is ahead of release or using it).

**Comment by mliebelt** [comment]
So I published the new version to npm, should be available from now on. Can you download the latest version?

**Comment by mliebelt** [comment]
Close the ticket for now, because I think it is solved. Please comment on it, if not.

**Comment by braoult** [comment]
Thanks, it is perfect, I had no time to answer yesterday (timezone issue).

However (I am unsure if it should be a separate issue), there is a display issue for result (`1-0`, `0-1`, etc...) when last move is black :

![image](https://user-images.githubusercontent.com/8958429/214785382-ea2139fb-99f9-4397-a70a-3ee0657ea4b1.png)

When last move is white, the display is correct :

![image](https://user-images.githubusercontent.com/8958429/214785744-f75b70cd-72e4-42e7-af2c-7cba8de2365f.png)

Maybe an option would be to always display the result below the last move line ?

**Comment by mliebelt** [comment]
It is a separate issue, so I would be glad if you could do that. Just PGN example, and the screenshot would be sufficient.
Thank you!
