### ISSUE TITLE
Wrong notation when we have same pieces in same line (eg rooks) (notation problem/BUG)

### ISSUE THREAD

**Issue by plirof** [mliebelt/PgnViewerJS#436]
Check in PGNviewerJS this FEN postition : 
rnbqkbnr/p1p2p2/3p2p1/R3p2p/7P/8/1PPPPPP1/RNBQKBN1 w kq - 0 8
Both white rooks are in column a.
Now if you move any othe two white rooks to a3 they both register as move **Ra3**
It should be registering the move as  **R5a3**  or **R1a3** but it just registers it as Ra3.
Lichess or any other chess program can't handle this.

This also goes to this Knight FEN
r1b1kbnr/p2q1p2/2n1p2p/R1pp2p1/1PPP3P/5N2/4PPP1/RNBQKB2 w kq - 4 12
If you move any of the knight in D2 it registers it as move : **Nd2**

**Comment by mliebelt** [comment]
I did the following to reproduce the error:

1. Went to https://mliebelt.github.io/PgnViewerJS/config/config.html (Configuration Builder).
2. Set there: modus == pgnEdit; fen from above.
3. Played the move on the board.

The problem is reproducible (thx for that), and it is only when producing the SAN notation. So the internal move has all information, but the creation of the SAN has flaws.

**Comment by mliebelt** [comment]
Ok, checked the code, is part of `pgn-reader`. I think I have to use the library `chess.js` to compute the SAN, there seems to be a library function available.

**Comment by plirof** [comment]
Is there a way to temp fix this before the 2.0 update? Can you point me what file to check?
I already use this for my son. I added save support, export PGN and send to lichess.org for analysis.
Thanks for your great work :)

**Comment by mliebelt** [comment]
The location of the [code is here](https://github.com/mliebelt/PgnViewerJS/blob/ba1869323d36cc71a21ff11b7d07b4c1bf8e982f/modules/pgn-reader/src/pgn.ts#L68), and the base idea to fix it is to use the library `chess.js` instead. I had planed to do that on the weekend, and if everything goes well to release a new patch version tomorrow. I  hope the use is not so complicated ...

So no need to fix it on yourself. Are your changes available in Github as well, so I could inform myself by looking at your fork?

**Comment by mliebelt** [comment]
Update: Seems not be so easy ... Reasons: My local version is broken somehow; had way too many automatic updates of Webpack, never tried locally; logic of producing the SAN is wrong (has to have the environment (current position) setup correctly, which is not yet there).

So it will take more time, I suspect.

**Comment by plirof** [comment]
Thanks that helped.
I used "beautify" on dist.js and got this part of code:
```
                         san(M) {
                            function A(M) {
                                return "P" === M ? "" : M
                            }
                            let N = M.notation;
                            if (void 0 === N.row) return N.notation;
                            const g = N.fig ? A(N.fig) : "";
                            let I = N.disc ? N.disc : "";
                            const j = N.strike ? N.strike : "";
                            j && !g && (I = M.from.substring(0, 1));
                            const D = N.check ? N.check : "",
                                t = N.promotion ? "=" + A(N.promotion.substring(1, 2)) : "";
                            return "short" === this.configuration.notation ? g + I + j + N.col + N.row + t + D : g + M.from + (N.strike ? j : "-") + M.to + t + D
                        }
```
I just replaced the "return" above with
`**return M.notation.notation;**`
and in my few test it seems to show the correct notation. Even lichess.org recognises it ok.
I don't know what san() tries to do but for my needs this dirty fix seems to work .

**Comment by mliebelt** [comment]
Seems to I have found a solution, but I want to check all edge cases. The goal is, that I have a valid solution, no workaround, able to find all (and only those) positions, where the disambiguator is needed. Will take some time on it, then release a patch version. As long as this ticket is open, the version is not released.

**Comment by mliebelt** [comment]
I have a first working solution, checked a little bit, and will release today a new version. Only then this ticket will be closed.
