### ISSUE TITLE
Allow FEN string with PGN to define start position from analysis

### ISSUE THREAD

**Issue by mliebelt** [mliebelt/PgnViewerJS#46]
I have the following use case very often:

1. I have a complete PGN (by analysis with the computer).
2. I want to publish part of it (definitiv not all of it) on the internet.
3. I take the FEN string from the current position.
4. I have to snip out the PGN from that position only.

It would be nice to have the following:

- Use the FEN string from above
- Use the whole PGN, but the viewer only displays the moves from the given position.

Alternative, it could be possible to see the whole PGN, but to show the game from the start position instead.

### Details

The following use cases may be interesting:

* Define the start position of the player by giving
   * a FEN string
   * a half-move number (counting from 1)
   * a move notation
The PgnViewer will then search for the right position.
* Define if moves should be
   * cut before (default?)
   * left complete

### Configuration

The configuration may be expanded by the following parameters. The example is the following PGN string: `1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-O Be7 6. c3 O-O 7. Re1 d5 8. exd5 Nxd5 9. Nxe5 Nxe5 10. Rxe5 c6 11. d4 Bd6 12. Re1 Qh4 13. g3 Qh3 14. Qd3`

* `startPlay`: no default. If not given, play starts from the first move. Possible values are
   * FEN string: `r1bq1rk1/1pp1bppp/p1n2n2/3pp3/B3P3/2P2N2/PP1P1PPP/RNBQR1K1 w - - 0 8` as start point of the main variation in Mashall gambit.
   * half-move number: 14 (which is the half-move of black in move 7).
   * move notation: `d5`
* `hideMovesBefore`: `true|false` (default false). If true hides the moves in the pgn notation which are before `startPlay`.

**Comment by awormuth** [comment]
This feature is incredibly useful! Great work. Is it possible to add to the documentation here? http://mliebelt.github.io/PgnViewerJS/docu/docu.html

**Comment by mliebelt** [comment]
Have a look at https://mliebelt.github.io/PgnViewerJS/docu/examples.html#1232, this is the only example that is contained in the documentation. The parameter is now named `startPlay`, but with the same meaning. I will update the original description of this ticket.

**Comment by mliebelt** [comment]
Just noticed that the implementation is not complete. the flag `hideMovesBefore` is not working.
