### ISSUE TITLE
pawn capture bug

### ISSUE THREAD

**Issue by LocutusOfPenguin** [mliebelt/PgnViewerJS#50]
Hi,

at least at the edit mode (in the example section of yr webpage), i get "xd6" instead of "exd6" for a move e5xd6.
Thats the case for ALL pawn captures.Other pieces captures are okay.

**Comment by mliebelt** [comment]
Do you have a concrete PGN for that? The disambiguation is only necessary if there are more than one possible moves to the same square. See the specification http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c8.2.3 (correct section 8.2.3.4).

Please add an example PGN, then I will have a look at it.

**Comment by LocutusOfPenguin** [comment]
its all on YOUR example webpage (in edit section). If i play d4,e5, dxe5, d6, exd6, Bxd6
i only get "xe5", "xd6" That looks buggy, and the FIDE approved dgt clocks also display "exd6", including "python-chess",.... and i would guess on chess books too.
So, its not about "disambiguation" instead about "captures"

**Comment by mliebelt** [comment]
Reread the specification, found there the following: 

> Capture moves are denoted by the lower case letter "x" immediately prior to the destination square; pawn captures include the file letter of the originating square of the capturing pawn immediately prior to the "x" character.

So you are right, I have to fix that. Will be in the next release (no big deal).

**Comment by mliebelt** [comment]
See the current release
