### ISSUE TITLE
Add an option to show board at a given move at page creation time (view / edit mode)

### ISSUE THREAD

**Issue by xeyownt** [mliebelt/PgnViewerJS#75]
An handy feature for my PgnJS mediawiki extension would be to show a given PGN game at a given move instead of the starting position.

For instance, one use case would be to have a wiki page that display most variation around a given opening (like `1. d4 d5`). We would have a table that shows all the main variation. Each cell would contain a board, with the set of moves, and the resulting position.

This is almost doable today, except that today all boards would display the same starting position and not the last one. So all boards would look alike, except for the move lists of course.

Ideally, I would prefer that we can specify the "focus" move as an attribute when calling `pgnView`. This would be the simpler for me. Alternatively, maybe could you tell me what javascript code I need to run after calling `pgnView` to achieve this result?

**Comment by xeyownt** [comment]
Note that another option would be to rely on the NAG `$220` if present, and automatically focus on that move (or first / last found) if present in the PGN.

**Comment by xeyownt** [comment]
Answering my own question, I just learned that we can do:
```javascript
$('#' + id + 'Buttonlast').trigger('click');
```
To simulate a click on the last button of board identified by `id`.

I wonder if it would be intereresting that the object returned by `pgnView` (and alike) would offer methods like `lastMove()`, `nextMove()`... ? This way we could drive the board with other means than the buttons. Then an interesting API would be something like `goToMove()` to go to a given move/variation.

For now I'll go with the line above, but having the option to use a `pgnView` attribute like `pgnView('b1', {pgn: pgn, goTo: 'last'})` would be really nice I think.

**Comment by mliebelt** [comment]
See the ticket #46 that defines a similar feature. To define the start move is not so easy, because neither the move number, nor the FEN string would be sufficient. I have to think what could be a "good" solution here. And I will have the need for an additional config parameter here ...

**Comment by xeyownt** [comment]
Coming back on this request, I see two solutions:
* Either use the existing NAG `$220` to indicate which position to focus on. If there are several of these, we could select the first. We could also foresee a *jump next* button to cycle through all such NAGs.
* Or specify the position with some binary tree coding. All n-ary trees can be encoded as binary trees. Every node in n-ary tree is mapped to a node in the binary tree. The first child of an n-ary node is the left child of the binary node. Then 2nd child is the left child of the right child, 3rd child is the left child of the "grand-right" child. If `N` is an n-ary node and `B` the corresponding binary node, we would have `N->child(0) == B->left()`, `N->child(1) = B->right()->left()`, `N->child(2) == B->right()->right()->left()`, and so on. So basically you use *left* to go down in the n-ary tree, and right to visit next child. Of course, this requires one or more extra *dummy* node for every node that has more than one child.
  Using this coding, we would then use an notation like `x.y.z` to specify a given move. `x` would indicate the x-th move on the mainline. `x.y` would indicate y-th move on the first variation starting at move x. Here `x.` denotes *take the right child of node x*. `x..y` would indicate the y-th move of the *second* variation starting at move x. `x..y.z` would indicate the z-th move of the first variation starting at move y, in the 2nd variation starting at move x. For clarity, `x`, `y`, `z` should be equal to the move number in PGN notation (so x < y < z).

Hope it's clear ;-)

**Comment by stanleyng8** [comment]
@xeyownt Can you clarify your workaround for jumping to a chosen startpoint? You said 
`$('#' + id + 'Buttonlast').trigger('click');`
Do you mean that you modify the pgn string and insert a #id into it like the following?
`1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 <div id='chosenposition'> 4. Ba4 Nf6 5. O-O Be7`
Then you trigger the above code on loading. 

If indeed the above is what you do, this involves modification of the PGN file. I was hoping that I won't have to do that. What about programmatically pressing the forward button the same number of times as the number of plys to reach the desired position? Do you have any reservations about this approach?

Thanks in advance for any input.

**Comment by mliebelt** [comment]
Please have a look at #46 again. There I have described the configuration that allows starting in the middle of the game. I did not add an additional NAG to PGN. $220 is already used to display that position in the moves, and I think I found a much simpler version that works well.

**Comment by mliebelt** [comment]
Please have a look at #46, I think this is a good enough solution without adding an arbitrary PGN code.
