### ISSUE TITLE
Great but a suggestion

### ISSUE THREAD

**Issue by kingvagabond** [mliebelt/PgnViewerJS#94]
This is a great tool but - I am not a beginner, so let me give a better advice:

Forget about chess.js. This library belongs to 10 years ago, because it does not support touch screen. You need to improve its code to make it work on mobile browsers.

Switch to chessground: https://github.com/ornicar/chessground. Use its js distribution code would be much better than chess.js.

**Comment by mliebelt** [comment]
As you may have noticed, there is a branch named Chessground, and I have begun to prepare a new release where the chessboard (not chess.js) will be replaced by Chessground. So stay tuned, I hope I will have it ready in a few days.

**Comment by kingvagabond** [comment]
That would be cool. I believe chessground is actually the so far best for GUI/board view. What chessground misses is PGN parser. chess.js has the ability for parsing PGN, but it's better to make view and parser as separate modules.

**Comment by mliebelt** [comment]
Have a look at the release 0.9.7, that now uses Chessground as the chessboard.
